### ISSUE TITLE
Make a .deb so we can continue to use getmail on debian

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#10]
Can you please make a .deb available?
As you can see I can no longer use getmail on debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968194

**Comment by rpuntaie** [comment]
I made a release v6.02.
Distro packages must be done by the according distros.

**Comment by jidanni** [comment]
Actually there is some serious problem on Debian that makes one unable to just do
$ python ...
like the installation instructions say.

- https://lists.debian.org/debian-python/2020/07/msg00044.html
- http://bugs.debian.org/968324
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968194 has no response yet too.

**Comment by jidanni** [comment]
Apparently there will be no "python" on any $PATH in Debian, only "python3".
So please make a release I can install on my Debian home machine without needing to not follow the instructions to the letter.

**Comment by Remmy** [comment]
jidanni, I feel this really is something for debian to fix/solve, either by providing a proper link to the python interpretator, or by packaging getmail6 with the appropiate changes made. I will however include a pointer for this in the installation instructions when I update them next.
