### ISSUE TITLE
redirect_uri requirements in Microsoft's OAuth 2.0

### ISSUE THREAD

**Issue by ykasap** [getmail6/getmail6#118]
I'm using getmail6 to retrieve messages from Microsoft Exchange Online via IMAP4 + OAuth 2.0.

In the pull request #115, redirect_uri is hard-coded as "http://127.0.0.1:(port number)/", but Microsoft's OAuth 2.0 has additional requirements for redirect_uri.

1. redirect_uri included in an authorization request must match with one of Redirect URIs in the application registration.
2. Each entry of Redirect URIs must start from "https" or "http://localhost".

So I cannot register http://127.0.0.1 as redirect_uri.  I'm not sure if there are similar requirements in other OAuth 2.0 implementations.  Is it okay to change 127.0.0.1 in redirect_uri to localhost in getmail-gmail-xoauth-tokens?  If not, what about reverting redirect_uri as configurable thru the input json file, but check if it points localhost or 127.0.0.1 ?

**Comment by rpuntaie** [comment]
I didn't try Microsoft, as I have no Microsoft email.
Would you make a pull request?
Would you also check and fix "Microsoft Office 365 xoauth2 example" in `docs/getmailrc-examples`?

**Comment by emtiu** [comment]
If I understand correctly, this is a regression for users of Microsoft OAuth. I'm holding off on updating the FreeBSD package until we know more.

**Comment by ykasap** [comment]
It worked for me when I registered http://localhost:8083/ in Redirect URIs of my getmail application in Azure AD and changed params['redirect_uri'] in the script from "127.0.0.1" to "localhost".  Probably "Example 13" in getmailrc-examples should be updated slightly.

**Comment by emtiu** [comment]
That's good to know, thanks! Could you write out what the section in getmailrc-examples should say?

**Comment by ykasap** [comment]
Oh, I thought that I needed to specify the port number when registering a Redirect URI, but actually not.  It seems fine to register "http://localhost" and specify any port number as redirect_uri.  So you don't need to update the example.

By the way, during testing I noticed that -p option (args.port) is a string, not an integer. 

```
Traceback (most recent call last):
  File "./getmail-gmail-xoauth-tokens", line 145, in <module>
    oauthd = OAuthRedirectServer(args.port)
  File "./getmail-gmail-xoauth-tokens", line 59, in __init__
    HTTPServer.__init__(self, ("127.0.0.1", server_port), OAuthRedirectHandler)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
TypeError: an integer is required (got type str)
```
