### ISSUE TITLE
Document how to cleanly remove getmail6

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#12]
README and docs/documentation.html mention
- installation

but neglect mentioning
- updating
- removal

(Maybe instead of tinkering with those files, just put all that bonus info into a new README.getmail6 .)

**Comment by Remmy** [comment]
Thanks. I am working on an update of the documentation in general. I hope to have a pull request ready by the weekend.

**Comment by emtiu** [comment]
This is now taken care of by 193c79159060e9ff7a6cdce6b87cb2ff02837c0d, which also closed #36, right?

**Comment by jidanni** [comment]
OK I guess. Right in time for the [future Debian maintainer](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969021) to use those instructions!
