### ISSUE TITLE
KeyError: 'to_oldmail_on_each_mail'

### ISSUE THREAD

**Issue by belasco** [getmail6/getmail6#120]
Don't usually report bugs, so please be gentle if I'm not doing this right or have missed something obvious. 
On using getmail today I have the following error:
```
Unhandled exception follows:
File "/home/dbr/.local/bin/getmail", line 1006, in main
   success = go(configs, options.idle)
File "/home/dbr/.local/bin/getmail", line 279, in go                         
    retriever.delivered(msgid)
File "/usr/lib/python3/dist-packages/getmailcore/_retrieverbases.py", line 981, in delivered
if self.app_options['to_oldmail_on_each_mail']:
KeyError: 'to_oldmail_on_each_mail'
```
Output of running with --dump:
```
getmail configuration:
  getmail version 6.18.9
  Python version 3.10.4 (main, Mar 24 2022, 13:07:27) [GCC 11.2.0]
  retriever:  SimplePOP3SSLRetriever(ca_certs="None", certfile="None", delete_dup_msgids="False", getmaildir="/home/dbr/.config/getmail", keyfile="None", password="*", password_command="()", 
port="995", server="mail.planbperformance.net", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_apop="False", username="dan@planbpe
rformance.net")
  destination:  Maildir(filemode="384", path="/home/dbr/Mail/mail/", user="None")
  options:
    delete : False
    delete_after : 7
    delete_bigger_than : 0
    delivered_to : True
    fingerprint : False
    logfile : None
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : None
    message_log_syslog : False
    message_log_verbose : False
    netrc_file : None
    read_all : False
    received : True
    skip_imap_fetch_size : False
    use_netrc : False
    verbose : 1
```
My rc file:

```
# -*- Mode: conf -*-
[options]
# delete = true
# try leaving stuff on so that I can access by phone for a week
delete_after = 7
read_all = False

[retriever]
type = SimplePOP3SSLRetriever
server = mail.planbperformance.net
username = dan@planbperformance.net
port = 995
password = *****

[destination]
type = Maildir
path = ~/Mail/mail/
```
Any help much appreciated :)

**Comment by rpuntaie** [comment]
I tried with and without `to_oldmail_on_each_mail = true` under `[options]` in the rc file: I could not reproduce the error using v6.18.9 and Python 3.10.4. It would be nice if you could investigate the reason. My setup could be slightly different in other ways.

**Comment by belasco** [comment]
Thanks so much, @rpuntaie  for trying for me. 
As you can see, I do not actually set `to_oldmail_on_each_mail` in my rc file. On a whim, I commented out `delete_after = 7`, and getmail worked: there was no error and the mail is fetched. 
However, that option (to delete emails on the server after they are 7 days old) is useful to me and I do not know why it has stopped working.

**Comment by belasco** [comment]
Hate to say this, but the issue has suddenly popped up again. I am happy to investigate but need some guidance where to look. I hackily commented out the following lines in `_retrieverbases.py` and got it to work.
```    
    def delivered(self, msgid):
        self.__delivered[msgid] = None
        # if self.app_options['to_oldmail_on_each_mail']:
        #     self.write_oldmailfile(self.mailbox_selected)
        #     self.__delivered = {}
```
I know that that is not a long term fix though and I don't understand why there is suddenly a key error reported from options when I can only see 'to_oldmail_on_each_mail' mentioned in this one line in the codebase.

**Comment by rpuntaie** [comment]
Does the above commit help?
