### ISSUE TITLE
upcoming: openssl 3 woes, such as weak ciphers unusable

### ISSUE THREAD

**Issue by miroR** [getmail6/getmail6#123]
With some mail servers, TLSv1 is the best they offer.
With one email provider, I have to set:
`ssl_version = tlsv1`
in my `$USER/.getmail/config/me@that-provider`
And that worked for years, until: some packages recently pulled libssl3, the new package from openssl source.
But openssl 3 wasn't pulled. I had compile and install it.
But no luck with TLSv1.
Probably, along with all the changes in this [OpenSSL 3 migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html), I might be experiencing:

> The security strength of SHA1 and MD5 based signatures in TLS has been reduced.
This results in SSL 3, TLS 1.0, TLS 1.1 and DTLS 1.0 no longer working at the default security level of 1 and instead requires security level 0. The security level can be changed either using the cipher string with @SECLEVEL, or calling SSL_CTX_set_security_level(3). This also means that where the signature algorithms extension is missing from a ClientHello then the handshake will fail in TLS 1.2 at security level 1. This is because, although this extension is optional, failing to provide one means that OpenSSL will fallback to a default set of signature algorithms. This default set requires the availability of SHA1.

When retrieving mail, all I get is:
`socket error ([SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:997))`

There is at the start of that Migration guide:

> OpenSSL 3.0 is a major release and consequently any application that currently uses an older version of OpenSSL will at the very least need to be recompiled in order to work with the new version. 

My programming skills are inadequate, so I can only ask: it this being worked on by somebody here? 
If I recompile getmail, from Debian git or from here, and make other necessary changes, any chance it'll work?

**Comment by emtiu** [comment]
Hi, thanks for pointing out this issue.

Since getmail6 is written in Python, it doesn't need to be (re-)compiled. But it will probably be necessary to adapt the getmail6 code, so getmail6 can convince OpenSSL 3 to use this very old, very weak encryption.

Is this a public email provider? It would be useful to have a server address for testing.

**Comment by emtiu** [comment]
Modifying `/etc/ssl/openssl.conf` was the missing hint. So now we've got reproducible test cases, which I'm documenting here as a well-defined starting point.

### getmailrc
```
[retriever]
type = SimplePOP3SSLRetriever
server = pop.t-com.hr
username = test
password = test

[destination]
type = MDA_external
path = /usr/bin/true

[options]
verbose = 1
read_all = 0
```
(In all cases, `ssl_version = tlsv1` seems to have no effect either way.)

### /etc/ssl/openssl.conf
```
[system_default_sect]
MinProtocol = SSLv3
CipherString = DEFAULT:@SECLEVEL=0
```
(Parameters found at the end of the file.)

## Working as expected
Vanilla Debian 11.3, with: OpenSSL 1.1.1n, Python 3.9.2, getmail6 6.14:
```
getmail version 6.14
Copyright (C) 1998-2020 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimplePOP3SSLRetriever:test@pop.t-com.hr:995:
getmailrc: operation error (POP error (b'-ERR Login failed.'))
  0 messages (0 bytes) retrieved, 0 skipped
```

## Not working
Debian Testing, with: OpenSSL 3.0.4, Python 3.10.5, getmail6 6.18.9:
```
getmail version 6.18.9
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimplePOP3SSLRetriever:test@pop.t-com.hr:995:
getmailrc: socket error ([SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997))
  0 messages (0 bytes) retrieved, 0 skipped
```

**Comment by emtiu** [comment]
There might be some more fundamental issue with the interaction between getmail6 and openssl. Looking at `_retrieverbases.py`, the `getmailrc` settings named `ssl_version` and `ssl_ciphers` should be picked up and applied to the connection.

But it seems like they have no effect on either OpenSSL 1.1.1 or 3.0.4. Only changes to `/etc/ssl/openssl.conf` help to get the weakly-encrypted connection underway (in the case of OpenSSL 1.1.1, anyway). This may or may not be related to [this recent API change](https://bugs.python.org/issue33570) in OpenSSL and its Python3 bindings.

For the moment, I'm out of ideas.

**Comment by emtiu** [comment]
I've got it. For OpenSSL 3.0.4 in Debian Testing, you need to add `ssl_ciphers = SSLv3` to the `[retriever]` section in your `getmailrc`. Note that this setting is **case sensitive**, so it must be `SSLv3`, not `sslv3`.

This `getmailrc` works as expected on Debian Testing with OpenSSL 3.0.4:
```
[retriever]
type = SimplePOP3SSLRetriever
server = pop.t-com.hr
username = test
password = test
ssl_version = tlsv1
ssl_ciphers = SSLv3

[destination]
type = MDA_external
path = /usr/bin/true

[options]
verbose = 1
read_all = 0
```

Please test, and close this issue if all is well.

**Comment by miroR** [comment]
> I've got it. For OpenSSL 3.0.4 in Debian Testing, you need to add `ssl_ciphers = SSLv3` to the `[retriever]` section in your `getmailrc`. Note that this setting is **case sensitive**, so it must be `SSLv3`, not `sslv3`.
> 
> This `getmailrc` works as expected on Debian Testing with OpenSSL 3.0.4:
> 
> ```
> [retriever]
> type = SimplePOP3SSLRetriever
> server = pop.t-com.hr
> username = test
> password = test
> ssl_version = tlsv1
> ssl_ciphers = SSLv3
> 
> [destination]
> type = MDA_external
> path = /usr/bin/true
> 
> [options]
> verbose = 1
> read_all = 0
> ```
> 
> Please test, and close this issue if all is well.

Thank you so much! It works. While studying openssl manual was right to do, I forgot that I should have re-read (old) getmail documentation as well. I wasn't even anymore aware there was the "ssl_ciphers" option.
Good find!
Regards!
