### ISSUE TITLE
Question: Does getmail6 use the IDLE capability of IMAP when multiple accounts are configured?

### ISSUE THREAD

**Issue by 0nelight** [getmail6/getmail6#126]
I use fetchmail at the moment, but want to use the Imap Idle Capability for multiple accounts.

I can spawn multiple fetchmail processes to be able to do that, but - besides of other advantages to fetchmail - I want to use getmail6 for that.

Is a single process in getmail6 enough for the Imap Idle capability with multiple accounts?

There is an argument "-idle" with getmail6 which is documented but I suspect the scope of the description there only refers to the argument, not to the actual capability of multiple accounts on one process.

Thank You

**Comment by rpuntaie** [comment]
getmail:

``` python
            help='maintain connection and listen for new messages in FOLDER. '
                 'Only applies if a single rc file is given with a connection '
                 'to an IMAP server that supports the IDLE command',
```

I checked. It is just like that.

- one rc file only

**Comment by 0nelight** [comment]
You checked only the helpfile with refers to watching a specific folder or you tested it?? thanks

**Comment by rpuntaie** [comment]
I checked the code against the help line. They fit together. For more accounts/rcfiles you would have to use one getmail process per account.
