### ISSUE TITLE
new google OAuth out-of-band

### ISSUE THREAD

**Issue by mabod** [getmail6/getmail6#127]
As of 3. October google chnages the way how  OAuth out-of-band (OOB) is working. In fact it will be deprecated.

https://developers.google.com/identity/protocols/oauth2/resources/oob-migration?hl=en

Is that something that will affect getmail6?

**Comment by rpuntaie** [comment]
It will not affect getmail-gmail-xoauth-tokens, as it has already an internal server for the redirect uri: no manual out-of-band copying any more.
