### ISSUE TITLE
6.18.9: MDA_external no (longer) working?

### ISSUE THREAD

**Issue by ChrisTG742** [getmail6/getmail6#128]
It seems that piping the email-content through stdin does no longer work. I tried the following setup under Ubuntu 20 that failed:

[retriever]
username = USER@DOMAIN.COM
use_xoauth2 = True
password_command = ("getmail-gmail-xoauth-tokens", "/home/user/.config/getmail/microsoft.json")
type = SimpleIMAPSSLRetriever
server = outlook.office365.com

[destination]
type = MDA_external
path = /bin/cat

This setup work perfectly if the destination is a Maildir or Mbox. In that case the message is placed there as expected.
When I try to use an external MDA, there is simply no content fed to stdin. I also tried with a python script that reads from stdin.
However, using --trace shows, that the email body actually is downloaded. So it must be dropped somewhere right before being fed to stdin.

**Comment by emtiu** [comment]
I'm using:
```
[destination]
type = MDA_external
path = /usr/local/libexec/dovecot/dovecot-lda
```
and it works as expected (on FreeBSD with getmail6-6.18.9).

You might want to try some other executable than /bin/cat, maybe something about its behavior has changed. Or it's a problem with paths, and the data might get written to somewhere other than you expect.

**Comment by ChrisTG742** [comment]
Thanks for your reply. I tried with several other binaries, including Bash- and Python-scripts. The result was always that there was no input from STDIN.
This always worked with Fetchmail from which I now have to switch since Microsoft will block non-OAuth Login soon and Fetchmail still does not support this.

**Comment by rpuntaie** [comment]
The test with MDA_external and path  '/bin/procmail' works.

Maybe you can investigate further on your side and possibly provide a pull request if you found something in getmail6.

**Comment by ChrisTG742** [comment]
Did you test with Ubuntu 20 LTS? Maybe it's connected to this particular distribution.
ATM I have no idea how to debug deeper in getmail6. Any hints?

**Comment by ChrisTG742** [comment]
Same with a fresh installed Ubuntu 22 LTS (getmail6 installed via PIP):

getmailrc:

[retriever]
username = user@somedomain.com
use_xoauth2 = True
password_command = ("getmail-gmail-xoauth-tokens", "/home/user/.config/getmail/microsoft.json")
type = SimpleIMAPSSLRetriever
server = outlook.office365.com

[destination]
type = MDA_external
path = /bin/cat
arguments = ("-",)


user@ubuntu22-test:~/.config/getmail$ getmail -v
getmail version 6.18.9
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:user@somedomain.com@outlook.office365.com:993: read_all and not delete -- all messages will be retrieved each time getmail is run
SimpleIMAPSSLRetriever:user@somedomain.com@outlook.office365.com:993:
  msg 1/2 (32562 bytes) delivered
  1 messages (32562 bytes) retrieved, 0 skipped
user@ubuntu22-test:~/.config/getmail$

No screen output at all...

**Comment by ykasap** [comment]
I believe that getmail handles the stdout of the external command as a status message and is not printed to the stdout of getmail as is.  Could you please try to use a script to send the stdin to a file?

**Comment by ChrisTG742** [comment]
@ykasap, thank a lot for the hint, you're brilliant! :)

Indeed that was the problem I was facing here. I never thought that getmail could just "suck up" the screen output of the called script.

I still think this should be changed as I see no reason why getmail should prevent the called MDA from writing to STDOUT and it differs from how fetchmail behaves.

Anyway, thanks a lot to all here for helping and sorry for the hassle! I'll close this issue here and open a new one with the proposal for aligning the behavior to like fetchmail does.
