### ISSUE TITLE
utf-8 decoding failes with Python 3

### ISSUE THREAD

**Issue by TIS-Stefan** [getmail6/getmail6#132]
Hello

I am doing my first steps with getmail6 on an outlook server. Using Python3 I get following error:
```
Delivery error (maildir delivery 4960 error (127, maildir delivery process failed ('utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte)))
  msg 1/1 (59022 bytes), delivery error (maildir delivery 4960 error (127, maildir delivery process failed ('utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte)))
```
Using python Python 2.7.16  works perfectly. (Annotation: Python2.7.18 causes trouble with no _ssl)

Stefan

**Comment by emtiu** [comment]
Sounds familiar – we've hit a few of these before: #49, #95. Maybe @rpuntaie remembers what he did there ;)

**Comment by rpuntaie** [comment]
Yes, a familiar and stubbornly recurring problem. I give it another try by using the `corrupted_message()` function instead of trying to replace/fix.

**Comment by rpuntaie** [comment]
@TIS-Stefan please give me some feedback whether it works or not.

**Comment by TIS-Stefan** [comment]
Good morning rpuntaie

I pulled and tested and have success! 

Well done. Case closed.

(Now starting to enable OAuth2,)

Stefan
