### ISSUE TITLE
imap socket error

### ISSUE THREAD

**Issue by mutable-dan** [getmail6/getmail6#133]
hello
i am getting the error:
Is there ann error in my config??

getmail version 6.18.4

SimpleIMAPRetriever:user@domain.com@domain.com:993: read_all and not delete -- all messages will be retrieved each time getmail is run
SimpleIMAPRetriever:user@domain.com@domain.com:993:
**user.config: operation error (IMAP error (socket error: EOF))**
  0 messages (0 bytes) retrieved, 0 skipped
  
**my config is**
`[retriever] 
type = SimpleIMAPRetriever
server = domain.com 
username = user@domain.com
port = 993 
password = ..........
mailboxes = ("INBOX", )

[destination]
type = Maildir
path = ./user/
`

thank you

**Comment by ChrisTG742** [comment]
Yup, there is. If you want to use IMAPS instead of IMAP, you'll need to use SimpleIMAPSSLRetriever instead:
https://getmail6.org/configuration.html#retriever-simpleimapssl
HTH

**Comment by mutable-dan** [comment]
thank you, it is working.  i didn't even notice the ssl

i am using it to download emails from one provider.  is it possible to use getmail to upload to a new imaps provider or send them to thunderbird?

thank you :)

**Comment by ChrisTG742** [comment]
You can use an external MDA to do so, have a look here:
https://getmail6.org/configuration.html#destination-mdaexternal

Some examples (not tested by me!):

[destination]
type = MDA_external
path = /usr/sbin/sendmail
arguments = ('-f', 'user@domain.local', '-oi', 'user@domain.local')

or:

[destination]
type = MDA_external
path = /usr/lib/dovecot/deliver
arguments = ('-d <username@localhost>', '-m Sent')

**Comment by ChrisTG742** [comment]
For Thunderbird it *might* be possible to deliver locally using the MBOX-format and specify any folder you Thunderbird-profile uses. AFAIR Thunderbird uses this? https://getmail6.org/configuration.html#destination-mboxrd
