### ISSUE TITLE
getmail-gmail-xoauth-tokens errors are confusing

### ISSUE THREAD

**Issue by XANi** [getmail6/getmail6#135]
Currently *any* error from MS side just gets trapped as `urllib.error.HTTPError: HTTP Error 401: Unauthorized` with no body of the error. It made debugging why the auth didn't work quite a bit harder than it should be (I was getting “AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.").

There should probably also be a mention that the app's redir should be added as web app, I had it added as "mobile and desktop application" (as I used that for claws-mail) and it didn't work

**Comment by ChrisTG742** [comment]
You're right, the hint which kind of app one needs to register, is actually yet missing in the readme.

**Comment by XANi** [comment]
Yeah we were very confused why we couldn't just reuse same app we used to authorize claws-mail.
