### ISSUE TITLE
How to initialize OAuth2 on machine with no browser on v6.18.10?

### ISSUE THREAD

**Issue by canute4444** [getmail6/getmail6#136]
How do I initialize the config on a headless machine?

I followed the Steps in `docs/getmailrc-examples`
On step 3, when I visit the URL on a different machine (PC), the URL leads to a localhost:8083 page
I have to visit the URL on a different machine because the machine running getmail on is headless and doesn't have a browser. On the PC, obviously that leads to `This site can't be reached` error message.

Previously, I used to simply get a code that I copy-pasted back to original machine and it worked.

**Comment by sufzoli** [comment]
If you connect to the headles machine (in my case an Ubuntu 18.04LTS) from a Windows, you can use PuTTY and redirect the 127.0.0.1:8083 port of the remote machine to your own machine. If you copy the link from the headless machine to your Windows browser, it will work (just used this scenario 10 min ago, so it is tested).

**Comment by ChrisTG742** [comment]
@canute4444 please see the updated [getmailrc-examples](https://github.com/getmail6/getmail6/blob/master/docs/getmailrc-examples) starting line 406.
Like @sufzoli said, the port 8083 needs to be forwarded as "localhost:8083" on your local machine where you actually run the browser.
HTH

**Comment by sufzoli** [comment]
@ChrisTG742, @canute4444 I wrote an entire blog post on the process, if you interested: https://pakahuszar.blogspot.com/2022/10/back-to-exchange-sort-of.html

**Comment by ilpingui** [comment]
@sufzoli this was really helpful. Can't seem to get it to work using a browser on OSX. Anything special i need to do besides `ssh -R 8083:127.0.0.1:8083` ?

**Comment by alpe12** [comment]
> How do I initialize the config on a headless machine?
> 
> I followed the Steps in `docs/getmailrc-examples` On step 3, when I visit the URL on a different machine (PC), the URL leads to a localhost:8083 page I have to visit the URL on a different machine because the machine running getmail on is headless and doesn't have a browser. On the PC, obviously that leads to `This site can't be reached` error message.
> 
> Previously, I used to simply get a code that I copy-pasted back to original machine and it worked.

Does the headless machine have curl?
If so, curl the url returned on the browser on the headless machine. That's what I do.
