### ISSUE TITLE
[request] Add mailbox name to log line.

### ISSUE THREAD

**Issue by rprimus** [getmail6/getmail6#137]
Sun 2 Oct 2022 17:23:55 BST

The current log format is:
```
2022-03-17 11:49:07 msg  8/12 (28231 bytes) msgid 135/12 from <unknown> delivered to Maildir [redacted-maildir]
```

`%(mailbox)` is available for destination `MDA_external` as well as in header `X-getmail-retrieved-from-mailbox`.

Can the `mailbox` be added to the logline as well?

**Comment by ChrisTG742** [comment]
Where do you exactly want it to be in the string?
If we think about adding efforts in this, maybe a "custom log" option that expands internal variables like `%(mailbox)` and others would make more sense?

**Comment by rprimus** [comment]
Fri 7 Oct 2022 11:06:40 BST

> Where do you exactly want it to be in the string?

Ideally, the mailbox would be placed before "msg":

e.g.

```
[github] msg 240/241 (141929 bytes) delivered
```
for v2:
```
2022-03-17 11:49:07 [github] msg  8/12 (28231 bytes) msgid 135/12 from <unknown> delivered to Maildir [redacted-maildir]
```

Currently, it's difficult to tell where messages are coming from.
```
  msg 240/241 (141929 bytes) delivered
  msg 241/241 (154868 bytes) delivered
  msg  9/10 (541833 bytes) delivered
  msg 10/10 (374532 bytes) delivered
  msg 230/230 (197721 bytes) delivered
  msg 68/71 (46956 bytes) delivered
  msg 69/71 (210359 bytes) delivered
  msg 70/71 (59399 bytes) delivered
  msg 71/71 (754559 bytes) delivered
  msg 153/184 (11259 bytes) delivered
```

**Comment by rprimus** [comment]
Sat 23 Mar 2024 16:34:21 GMT

@rpuntaie Thank you very much!! ❤️
