### ISSUE TITLE
How to mark emails as read on the server?

### ISSUE THREAD

**Issue by giovEra** [getmail6/getmail6#141]
Is there an option to mark all emails downloaded with getmail as read?
I've been gazing at the documentation and can't seem to find how to do it.

Thanks

**Comment by emtiu** [comment]
Do you mean marking them as read _on the server_ you're downloading the mails **from**, or _in the destination mailbox_ you're downloading them **into**?

**Comment by giovEra** [comment]
I would like the emails, downloaded by getmail, to be marked as read on the server side.
Instead, it doesn't matter to me if they are marked as read in the mbox file generated by getmail.

**Comment by rpuntaie** [comment]
There is an example in prepare_test.sh

```
getmail --rcfile=getmail --getmaildir=/home/getmail --searchset UNSEEN --searchset ,SEEN
```

See also

https://www.rfc-editor.org/rfc/rfc3501#:~:text=flags%20message%20attribute
