### ISSUE TITLE
Exchange Online oauth Token not renewing

### ISSUE THREAD

**Issue by VinnieNZ** [getmail6/getmail6#145]
I've successfully managed to follow the example and setup an IMAP connection from getmail 6.18.10 to Exchange Online and get a working token.

This is on an Ubuntu headless server.

However, after a period of time (looks to be about 1 hour after first obtaining the initial token), it just stops working and starts to throw this error in the getmail log:
`getmailOperationError error (External program error (getmail-gmail-xoauth-tokens exited with 1))`

Running "getmail-gmail-xoauth-tokens /home/username/.getmail/microsoft.json" produces the following output:
```
Traceback (most recent call last):
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 153, in <module>
    print("%s" % auth.token())
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 125, in token
    self.refresh_tokens()
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 117, in refresh_tokens
    params = self.copy('client_id', 'client_secret', 'refresh_token')
  File "/usr/local/bin/getmail-gmail-xoauth-tokens", line 73, in copy
    data[k] = self.data[k]
KeyError: 'refresh_token'
```

The only way I can get it working again is to rerun the above command with the -i flag and go through the process of logging in to get the token.

Then it works for an hour again and stops.

**Comment by rpuntaie** [comment]
I have no Microsoft mail, but I had the problem with the access token getting outdated in google, too. One has to initialize (-i) again and again. Can this be automated?
If so, a pull request is very welcome.

Google provides app password as described in the README. I use that now.

**Comment by ykasap** [comment]
I don't have this problem, and using my getmail6 instances for a very long time (more than several months) without signing in again.

I just noticed that example 13 in docs/getmailrc-examples didn't include one more app permission, "offline_access," in addition to IMAP/POP/SMTP permissions. I believe it is necessary to obtain a refresh token, which is used to get a new access token when the old token expires. My JSON file contains a refresh_token in addition to an access_token.

**Comment by VinnieNZ** [comment]
Confirm that making the changes to the .json file and to the API Permissions has resolved this problem and I've had about 16 hours worth of successful IMAP downloads.
