### ISSUE TITLE
Error when using 'getmail-gmail-xoauth-tokens' -> getmail-gmail-xoauth-tokens  is not recognized as an internal command

### ISSUE THREAD

**Issue by J34NP** [getmail6/getmail6#150]
Hey everyone; due to the changes upon Imap utilisation with microsoft, i had to find a new way to listen to incoming email, i am following this "tutorial' which has the same problem as me. [https://www.redmine.org/issues/37688#note-17]

my problem is that i can't even execute the first command "getmail-gmail-xoauth-tokens".
here is the error i get with a normal command block (in french)  : `getmail6\configuration\data>getmail-gmail-xoauth-tokens ~/.getmail/provider.json
'getmail-gmail-xoauth-tokens' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.`

and here is my "provider.json" : 
`{
  "user": "developpement@mydomain.com",
  "scope": "offline_access https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/POP.AccessAsUser.All https://outlook.office.com/SMTP.Send",
  "client_id": "myclientIdFromAzure",
  "client_secret": "MyClientSecretFromAzure",
  "tenant": "common",
  "auth_uri": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
 	  "token_uri": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
 	  "redirect_uri": "http://localhost:10101"
}`

And finally, here is my "getmailrc" (the one commented is a try that didn't work either) : 
`#[retriever]
#type = SimpleIMAPSSLRetriever
#server = smtp.office365.com
#port = 587 
#username =me@mydomain.com
#password = mypassword
#
#[destination]
#type = Maildir
#path = ~/Mail/<me@mydomain.com>/helpdesk-test/
#
#[options]
#read_all = true
#delete = false

#another try that i did
[retriever]
type = SimpleIMAPSSLRetriever
server = outlook.office365.com
username = me@mydomain.com
password_command = ("getmail-gmail-xoauth-tokens", "C:\Users\jpa\Documents\getmail test\getmail6\configuration\data\provider.json")
use_xoauth2 = true

[destination]
type = MDA_external
path = C:\Bitnami\redmine-4.1.1-1\apps\redmine\htdocs\extra\mail_handler\rdm-mailhandler.rb
arguments = ("--url=http://localhost/redmine/admin", "--key-file=/home/redmine/ws-api-key.txt", "--certificate-bundle=/home/redmine/certs/cacert.pem")
#type = Maildir
#path = C:\Users\jpa\.getmail\Maildir\

[options]
read_all = false`

I looked on some issues found on this repository but none of them  were like mine.

i hope that you'll be able to help me 

if you need any complementary information don't bother asking

**Comment by ChrisTG742** [comment]
Did you clone the whole folder-structure? Looks like you're running Windows, so did you create a virtual environment for Python?
If not, it could easily be that the file "getmail-gmail-xoauth-tokens" is simply not found by the main script.
Another work-around could be that you specify the full path there:
```
password_command = ("C:\path-to\getmail6-dir\getmail-gmail-xoauth-tokens", "C:\Users\jpa\Documents\getmail test\getmail6\configuration\data\provider.json")
```
