### ISSUE TITLE
Running getmail6 as a service - in Docker

### ISSUE THREAD

**Issue by danwie** [getmail6/getmail6#154]
What is the preferred way of running getmail6 as a service in IMAP IDLE mode in a Docker container? What I need is getmail6 to restart if it stops waiting. For example if there is a problem with the Internet connection

**Comment by rpuntaie** [comment]
There are so many options to start/restart processes in docker.  Maybe continue here: https://docs.docker.com/config/containers/multi-service_container/

getmail6 is just a python script. So python is the process that runs the getmail6 script. python=python3.

**Comment by danwie** [comment]
Thanks. What exactly happens when getmail stops waiting. If the Internet connection is lost. Does the process end?
