### ISSUE TITLE
Slow initialization

### ISSUE THREAD

**Issue by cshelton** [getmail6/getmail6#155]
I upgraded my system which included installing python 3.11 (from 3.10).  This also required reinstalling getmail6.  Since then, I've noticed that getmail takes a long time to complete.  Perhaps this is due to the changes with the upgrade.  Perhaps I've only just now noticed it.

Specifically:
```
[vmail@gloomhaven getmail6-6.15]$ python --version
Python 3.11.1
[vmail@gloomhaven getmail6-6.15]$ time python -c "import socket; print(socket.getfqdn())"
gloomhaven.local

real	0m1.395s
user	0m0.021s
sys	0m0.007s
[vmail@gloomhaven getmail6-6.15]$ time getmail --version
getmail 6.15

real	0m15.435s
user	0m0.201s
sys	0m0.036s
```

You'll notice that it takes 15 seconds for getmail to print its version.  Rearranging a few lines in the getmail script, I believe this is due to the "from getmailcore import retrievers" (or destinations, or anything else other than \_\_version__ or \_\_license__ from getmailcore).  Beyond that, I'm uncertain what is causing the problem.

The getmailcore module is being loaded from getmail6-6.15-py3.11.egg which was installed standardly (in ~/.local/...) through the setup.py script supplied with the tarball.  

Any suggestions on what I can do to improve this would be helpful (the same delay occurs when trying to fetch mail, which is the real issue).

**Comment by rpuntaie** [comment]
My guess: it goes remote according `$(XDG_CONFIG_HOME}/getmail/*` and can't reach the specified server.
I know, why going remote on `--version`?

**Comment by cshelton** [comment]
Thanks.

Hmmm... XDG_CONFIG_HOME isn't specified.  So, I believe it should default to ~/.config.  There is no ~/.config/getmail (or similar).  Specifying a configuration file (via -r flag) doesn't change anything.  I have two rcfiles.  Both reach the server and obtain mail just fine, but don't start doing so until after 15 seconds.  

Killing (via ctrl-C) the process a few second in yields

```
Traceback (most recent call last):
  File "/home/vmail/.local/bin/getmail", line 4, in <module>
    __import__('pkg_resources').run_script('getmail6==6.15', 'getmail')
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/home/vmail/.local/lib/python3.11/site-packages/getmail6-6.15-py3.11.egg/EGG-INFO/scripts/getmail", line 68, in <module>
  File "/home/vmail/.local/lib/python3.11/site-packages/getmail6-6.15-py3.11.egg/getmailcore/retrievers.py", line 371, in <module>
  File "/home/vmail/.local/lib/python3.11/site-packages/getmail6-6.15-py3.11.egg/getmailcore/retrievers.py", line 397, in SimpleIMAPRetriever
  File "/home/vmail/.local/lib/python3.11/site-packages/getmail6-6.15-py3.11.egg/getmailcore/utilities.py", line 502, in localhostname
  File "/usr/lib64/python3.11/socket.py", line 794, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
                                 ^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
'''

My test above (which I have repeated) suggests that calling getfqdn with a blank string (and I've also tried with the hostname) takes about 1.3 seconds.  The line in utilities.py seems to be calling socket.getfqdn() directly.  Instrumenting sockey.py suggests that (even with "--version"), getmail is calling socket.getfqdn() 11 times on start-up.  My socket.getfqdn() takes about 1.3 seconds (and perhaps that's the problem) which explains the 15 seconds on start up.  nslookup on the command line is instantaneous for any reasonable query (and returns the same information).

So, there seem to be two "culprits:"  1.  the "gethostbyaddr" call in "getfqdn" takes over a second (which seems long) and 2. getmail calls this 11 times.  The combination of the two is leading to a long start-up phase for getmail.

I've checked my network set-up to see if there is something amiss that is causing gethostbyaddr to take more than a second.  I cannot find something, but I'll keep looking.

**Comment by rpuntaie** [comment]
It is most likely a local issue,
considering the absence of such  reports so far.
I close this.
But please report  to inform those who read this, in case you find the reason.

**Comment by cshelton** [comment]
If others aren't having this issue, then it probably is something local, so reasonable to close.  I cannot determine anything that would make the python "gethostbyaddr" call take a long time (especially when any command line host/ip/addr commands take msecs).  

It looks like in getmailcore, every Retriever class sets its own "received_by" member by calling localhostname().  That probably accounts for the 11 such calls at start up.  If each takes 10ms, that's fine.  If each takes 1sec, that's a delay of 11 seconds.  I guess I'm unlucky to be in the latter situation :(

If I do find some configuration that is causing this, I'll post it, even if it is particular to my own system.

Thanks.
