### ISSUE TITLE
Continue after error in child

### ISSUE THREAD

**Issue by TIS-Stefan** [getmail6/getmail6#156]
Hello

I have a similar, but different issue

getmailOperationError error (child pid 26276 killed by signal 6)
2023-01-06 09:32:02   1 messages (158524 bytes) retrieved, 0 skipped

The process was in procmail and there is somewhere a memory corruption error. Seems to happen with some mails from google. Unfortunately, getmail stops processing following mails.
Same, but with another signal and not in procmail happens with some particular emails from DHL with attachment.
If I remove the emails in question from the inbox, then all works fine again. I run the getmail6 every two minutes.

What I would like to do is:
If there is an error, ignore it and continue with next mails in the queue. Is that possible? How do I need to change the getmail6 code?

I see the logs anyway and therefore can handle that.

Thank you in advance!

Stefan

**Comment by rpuntaie** [comment]
This is a continuation from #64.

I think getmail6 should not die due to one mail in the first place
instead of accepting that and doing some workaround.

It might be an encoding issue. The last change in this regard was #91 released in v6.18.4. Currently we are v6.18.11.

I don't know which version you have,
but could you try the newest version?

**Comment by TIS-Stefan** [comment]
Hi

Thank you for you answer. It seems, I was 22 commits behind master and pulled now. I had a difference in getmail-gmail-xoauth-tokens.  Maybe caused by something with MS-Exchange stuff.
So, lets see, how it continues. 

I also do not think, the child process being aborted is an issue of getmail6, but rather of sendmail called by procmail, which causes a malloc() memory corruption on some mails, from google and dhl. Also weird: If I move the mail on the Exchange server into another directory and copy it back into the inbox, it will be processed flawlessly. 

I looked into baseclasses.py at 
* forkchild()
* _wait_for_child()
I see, that in in _wait_for_child() is an exception "raise getmailOperationError()" is done, but I was not able to figure out, where the exception is caught. Thus, as unexperienced as I am, I would simple make the lines 448 to 452 as comment.
```Python
       if os.WIFSIGNALED(self.__child_status):
            raise getmailOperationError(
                'child pid %d killed by signal %d'
                % (self.__child_pid, os.WTERMSIG(self.__child_status))
            )
```
But I suppose, that will raise other issues. 

My goal is to ignore the issue caused by procmail and continue processing the remaining emails in the queue. 

Stefan

**Comment by TIS-Stefan** [comment]
Thank you for coming answering so fast. I agree, I do not want to manipulate the current code, as I do not suspect it being wrong at all. I suppose, there error is somewhere in my procmail stuff. 

I just found the option `ignore_stderr=true`. Maybe it does, what I need. 

Stefan

**Comment by TIS-Stefan** [comment]
Good Morning!

Unfortunately the ignore_stderr=true has not the wanted effect.  However, this time the error did not happen in procmail. The documentation says:

> ignore_stderr ([boolean](https://getmail6.org/configuration.html#parameter-boolean)) — if set, getmail will not consider it an error if the program writes to stderr. The default is false, which causes getmail to consider the delivery failed and leave the message on the server, proceeding to the next message.

(from https://getmail6.org/configuration.html)

The log says
```
2023-01-10 08:34:02 getmailOperationError error (child pid 22256 killed by signal 11)
2023-01-10 08:34:02   1 messages (388787 bytes) retrieved, 0 skipped
```
signal 11 is SIGSEGV. 
And the next mails are not processed.
I assume, the error happens, when the bad mail is deleted from the IMAP server, but I do not know, it is not logged, which program or thread is started.
After removing the bad mail (from dhl.com) from the inbox, all following messages are proceeded successfully. 

The config file contains
```
[destination]
type = MDA_external
path = /usr/bin/procmail
unixfrom = True
arguments = ('-m','procmailrc', '-f', 'Received : %(sender)')
user = me
ignore_stderr=true

[options]
read_all = False
delete = true
ignore_stderr=true
verbose = 2
message_log_verbose = true
message_log = /home/getmail.log
```
Is there a way getting more logging information? 

Also: I delete the processed email from the local inbox in procmail. Could that have an effect too?
```
# Delete from local inbox
:0
/dev/null
```
If I do not delete the mail from the local inbox, I get procmail delivery errors and a mail is not even deleted from the email server and processed again and again. 

(I must do a lot of processing for handling the mails...)

I am aware, it is a stupid situation and it is my issue only. Therefore, please do not be too annoyed by me. 

Thank you in advance!
Stefan

**Comment by rpuntaie** [comment]
`--trace`  print extended debugging information

I think there is a principle problem. `destinations.py` is supposed to raise `getmailDeliveryError` and not `getmailOperationError`. I will fix this very soon.
 
Thank you for being persistent. A software needs poking.

**Comment by TIS-Stefan** [comment]
I added --trace and got:
```
write_oldmailfile() [_retrieverbases.py:915] mailbox=INBOX__str__() [retrievers.py:456] trace
(...)
sgid 14/172838 ...
 timestamp 1671099481
msgid 14/175200 ...
 timestamp 1672732681
msgid 14/172976 ...
 timestamp 1671143401
msgid 14/174858 ...
 timestamp 1672227481
msgid 14/174243 ...
 timestamp 1671677881
msgid 14/174049 ...
 timestamp 1671622201
msgid 14/175783 ...
 timestamp 1672922281
msgid 14/172525 ...
 timestamp 1671021721
msgid 14/174297 ...
 timestamp 1671700922
msgid 14/173720 ...
 timestamp 1671538442
msgid 14/174384 ...
 timestamp 1671718201
msgid 14/174246 ...
 timestamp 1671688801
msgid 14/176523 ...
 timestamp 1673270402
msgid 14/175242 ...
 timestamp 1672741441
msgid 14/175048 ...
 timestamp 1672564681
msgid 14/175182 ...
 timestamp 1672728481
msgid 14/173970 ...
 timestamp 1671613561
msgid 14/173487 ...
 timestamp 1671455281
msgid 14/172451 ...
 timestamp 1671009002
msgid 14/175074 ...
 timestamp 1672647481
msgid 14/172096 ...
 timestamp 1670878442
msgid 14/174381 ...
 timestamp 1671717482
msgid 14/172077 ...
 timestamp 1670871241
msgid 14/172247 ...
 timestamp 1670938921
msgid 14/176019 ...
 timestamp 1672998241
wrote 1727 uids for SimpleIMAPSSLRetriever:bla@bla@xxxxx.com:993:INBOX

```
Is that something important?

Stefan

**Comment by rpuntaie** [comment]
The traces would need to show the problem, i.e. encounter a problematic email.
Anyway I'm about to commit some changes. It would be nice if you tested with such an email.

**Comment by TIS-Stefan** [comment]
The problem is, after moving the mail around in Outlook on the exchange server, the issue does not happen....

See me really confused.

I pulled your changes and lets see, what happens. 

Stefan

**Comment by TIS-Stefan** [comment]
Hello

The error did not happen since two weeks, but the "bad" mails did not happen to appear. 
Therefore, I close the case for now.

Thank you very much for your update and help!

Stefan
