### ISSUE TITLE
What is the content in the file oldmail-pop.xx.com-995-xxx@xx.com generated based on

### ISSUE THREAD

**Issue by wanghao75** [getmail6/getmail6#163]
I want to know  what is the content in the file, it has any relation with email, thks

**Comment by emtiu** [comment]
It stores the information, which e-mails have already been downloaded from that server. If you keep your e-mails on the server (no delete after download), then this makes sure the same messages are not downloaded again.

**Comment by wanghao75** [comment]
got it, thanks for your reply, I will close this issue
