### ISSUE TITLE
First time user experience: Setting up maildirs recursively and for the first time

### ISSUE THREAD

**Issue by doronbehar** [getmail6/getmail6#164]
Hello,

First time trying to use `getmail`, considering to switch to it due to [mbsync's lack of imap IDLE support](https://sourceforge.net/p/isync/feature-requests/11/).

Reading getmail's documentation, up to configuration file format changes, I expected a similar experience to that of mbsync, only with the `--idle` option. However, I was disappointed from the maildir support.

Quoting the docs:

> The Maildir destination delivers to a qmail-style [maildir](http://cr.yp.to/proto/maildir.html). The maildir must already exist, and must contain all of the subdirectories required by the maildir format. getmail will not create the maildir if it does not exist. If you're not familiar with the maildir format, the requirements in a nutshell are: it must be a directory containing three writable subdirectories cur, new, and tmp, and they must all reside on the same filesystem.

So, if I want to setup getmail for the first time to retrieve all of my messages for the first time, how do I do that?

Reading the error messages by `getmail`:

```
Configuration error: configuration file /home/doron/.config/getmail/gmail.rc incorrect (path: maildir subdirectory ".../gmail.getmail/{cur,new,tmp}" does not exist)
```

I created all of these subdirectories, and getmail finally ran fine, but it deleted all of my messages! Lucky me I was sharp enough to understand the log messages:

```
  msg 1/9 (7826 bytes) delivered, deleted
  msg 2/9 (3910 bytes) delivered, deleted
  msg 3/9 (6538 bytes) delivered, deleted
  ...
```

And lucky me I had only 2 important messages in my `INBOX` so the damage wasn't too brutal.

I also noticed, that although I used:

```
mailboxes = ALL
```

`getmail` didn't create the maildirs recursively in `.../gmail.getmail`. Is there a way to tell it to discover server labels and add `[Gmail]/Sent` and `[Gmail]/Drafts` maildirs locally?

**Comment by rpuntaie** [comment]
- The creation of the maildir folders is just a one-time action.

```
 mkdir -p /path/to/Maildir/{cur,new,tmp}
```

 Either you find it in the docs or the error message tells you.

- Deleting from server or not is controlled by

```
[options]
delete = true
```

As for producing local folders for gmail labels, one can make a separate config file for each folder:

```
foo.rc:
  [retriever]
  [...]
  mailboxes = ("model-railroading", )

  [destination]
  type = Maildir
  path = ~/Mail/hobbies/railroads/

bar.rc:
  [retriever]
  [...]
  mailboxes = ("work", )

  [destination]
  type = Maildir
  path = ~/Mail/inbox/
```

(src: https://marc.info/?l=getmail&m=151536817916770&w=2)
