### ISSUE TITLE
Fails trying to deliver email with broken emojis

### ISSUE THREAD

**Issue by h3xx** [getmail6/getmail6#169]
Yes, I download my spam. :-)

The content of the mail message really shouldn't affect whether it can be delivered.
Also, since mail is usually transmitted using a [7-bit ASCII protocol](https://www.rfc-editor.org/rfc/rfc821), **IMO all the faffing about with Unicode decoding/encoding in the code is wrong-headed at best** &mdash; it shouldn't really care if my mail message is proper Unicode, much less *fail* if it isn't.

Here's the error message:
> failed to parse retrieved message; constructing container for contents
> Delivery error (maildir delivery 757 error (127, maildir delivery process failed (%b requires a bytes-like object, or an object that implements __bytes__, not 'UnicodeEncodeError')))

# 📎 [spam.eml.gz](https://github.com/getmail6/getmail6/files/12362320/spam.eml.gz)

# Steps to Reproduce
1. Decompress (`gzip -d spam.eml.gz`).
2. Upload the attached message as-is in to your favorite INBOX.
    (You may need to use an email client such as Thunderbird or Mutt; I don't think the GMail web interface allows you to import .eml files.)

<details>
<summary>I actually used this Perl program to upload to my gmx.com inbox (~20 lines):</summary>

```perl
#!/usr/bin/perl
use strict;
use warnings;
require Net::IMAP::Client;
my $imap = Net::IMAP::Client->new(
    server => 'imap.gmx.com',
    ssl => 1,
    port => 993,
) or die 'Could not connect to IMAP server';
unless ($imap->login('<MY LOGIN>', '<MY PASSWORD>')) {
    die 'Login failed: ' . $imap->last_error;
}
open my $eml_h, '<', 'spam.eml' or die "Failed to open spam.eml: $!";
my $email;
{local $/; $email = <$eml_h>} # slurp!
close $eml_h;

unless ($imap->append('INBOX', \$email)) {
    die 'Append failed: ' . $imap->last_error;
}
```

</details>

3. Attempt to download your mail from said inbox.
    This is the .rc file used:

```rc
[options]
delete = true
message_log = ~/.log/getmail.log
use_netrc = true

[retriever]
type = SimpleIMAPSSLRetriever
server = imap.gmx.com
mailboxes = ("Spam",)
record_mailbox = false

[destination]
type = Maildir
path = ~/Maildir/.Spam/
```
This is how getmail was invoked:
```sh
getmail -r ~/.getmail/spam.rc
```

- Getmail6 version: a83722c11f69ec41af14f8e5d5b30a540e640eec
- Python version: 3.9.17
- imaplib 2.58 (shipped with Python 3)

Note: I couldn't getmail to run under Python2, so I don't know if this affects Python 2.

**Comment by rpuntaie** [comment]
Thanks. I'll make a test case with this.

Regarding the "faffing with Unicode", I agree, and pull request are appreciated.

**Comment by h3xx** [comment]
Thanks for looking into this so thoroughly. I'm not skilled in Python, so your expertise really helps. :-)

Guess I have a bug or two to report.
