### ISSUE TITLE
Is v6.18.13 the latest release?

### ISSUE THREAD

**Issue by p-linnane** [getmail6/getmail6#171]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v6.18.13 of getmail6 we noticed that a release was not created on GitHub. Wanted to confirm if this was intentional, as we don't want to update our package to a version that is not the latest stable. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/140230

**Comment by rpuntaie** [comment]
Done. Thanks for the heads-up.

**Comment by p-linnane** [comment]
Thank you!
