### ISSUE TITLE
spf check

### ISSUE THREAD

**Issue by spi43984** [getmail6/getmail6#174]
I am using getmail + postfix to retrieve mails over imap from different mailboxes. Unfortunately my mail provider doesn't do any spf checks and therefore doesn't add any `Received-SPF:` header.

As getmail uses postfix' sendmail to process incoming mails (mails are not forwarded on tcp port 25 to postfix but rather placed by postdrop in a queue file in the maildrop directory, then picked up by postfix and processed further) I can't use postfix-policyd-spf to do the spf check either (it seems to support the smtpd daemon only and doesn't seem to work with the pickup one).

So I wonder if anybody used getmail's filter to run spf checks. The envelope sender address is available, the delivering mail server is the last one in the received header - so there should be the required information to paste the mail into a filter script to verify and create a spf header.

Cheers
spi

**Comment by emtiu** [comment]
I might be missing the point here, but: You have plenty of options what getmail should do with your messages. I don't have the incoming mail processed by postfix, for example, but filtered by dovecot with Sieve rules and deposited into the appropriate Maildir folders.

I do this with the following config entries:
```
[destination]
type = MDA_external
path = /usr/local/libexec/dovecot/dovecot-lda
```

Check out getmail's documentation here: https://getmail6.org/configuration.html#conf-destination

**Comment by spi43984** [comment]
It's not about filtering - for that I use sieve as well.

What I'd like to achieve is to do a proper spf check and add a spf header accordingly so it could be used by other tools further down the line to e. g. increase spam detection (https://en.wikipedia.org/wiki/Sender_Policy_Framework). This is usually done by the receiving MTA as envelope from, helo name, sender IP etc. are needed for this check to be performed. As I don't operate my MTA to receive mails directly but rather inject them by getmail I can't implement this kind of check in my MTA.

**Comment by rpuntaie** [comment]
You could possibly use https://github.com/sdgathman/pyspf/ after getmail.

**Comment by spi43984** [comment]
> You could possibly use https://github.com/sdgathman/pyspf/ after getmail.

That's a good idea. Would need a wrapper though to create the correct header and inject it back into the mail. Did some more testing - quite challenging to implement all the checks in my getmail + postfix + dovecot tool chain. Need to evaluate that further - it might be easier to change the tool chain at all.
