### ISSUE TITLE
UnicodeDecodeError when checking mail

### ISSUE THREAD

**Issue by jlesieutre** [getmail6/getmail6#180]
I get the following error:

```
  getmail version 6.18.13
  Python version 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]

Unhandled exception follows:
    File "/usr/bin/getmail", line 1022, in main
    success = go(configs, options.idle)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/bin/getmail", line 193, in go
    retriever.select_mailbox(mailbox)
    File "/usr/lib/python3.11/site-packages/getmailcore/_retrieverbases.py", line 1468, in select_mailbox
    self.read_oldmailfile(mailbox)
    File "/usr/lib/python3.11/site-packages/getmailcore/_retrieverbases.py", line 884, in read_oldmailfile
    for line in f:
    File "<frozen codecs>", line 322, in decode
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 4375: invalid start byte
```

Settings info from `--dump`:

```
getmail version 6.18.13
Copyright (C) 1998-2023 Charles Cazabon and others. Licensed under GNU GPL version 2.
getmail configuration:
  getmail version 6.18.13
  Python version 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
  retriever:  SimpleIMAPSSLRetriever(ca_certs="None", certfile="None", getmaildir="/home/johnl/.config/getmail", imap_on_delete="None", imap_search="None", keyfile="None", mailboxes="('INBOX',)", move_on_delete="None", password="*", password_command="()", port="993", record_mailbox="True", server="posteo.de", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_cram_md5="False", use_kerberos="False", use_peek="True", use_xoauth2="False", username="john.lesieutre@posteo.net")
  destination:  Maildir(filemode="384", path="/home/johnl/mail/unsorted/", user="None")
  options:
    delete : False
    delete_after : 0
    delete_bigger_than : 0
    delivered_to : True
    fingerprint : False
    logfile : logfile(filename="/tmp/getmail.log.posteo")
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : /tmp/getmail.log.posteo
    message_log_syslog : False
    message_log_verbose : False
    netrc_file : None
    read_all : False
    received : True
    skip_imap_fetch_size : False
    to_oldmail_on_each_mail : False
    use_netrc : False
    verbose : 1
```
I'm using the ArchLinux getmail6 package from the AUR.  I see there have been some similar issues in the past, apologies if this is a duplicate somehow!

**Comment by emtiu** [comment]
Thanks for your report! Can you identify some specific message that triggers this error? The answer probably lies in the source of one specific e-mail.

Be careful not to: 1) delete any messages accidentally in testing or 2) publish private information from any message here :)

Feel free to discuss the next steps for diagnosis here if you're unsure.

**Comment by jlesieutre** [comment]
Could you give me a hint what to search for?  (And perhaps how to search? Everything goes to a maildir.)  Would it be a message already delivered or one of the next ones on the server? 

I'd already tried deleting the first few unfetched ones from the server and it didn't help, but there are probably others that have been present since I started getting the message.

Thanks for the help and for running the project; I apologize for my debugging ignorance.

**Comment by emtiu** [comment]
Hmm, I'm not sure either. I would have tried the same things as you. Some parts of your error message make me think that the `oldmail`-file might be part of the problem. You might move it away from your config directory and try then.

Careful, though: If you keep messages on the server (instead of deleting them), removing the oldmail-file will cause getmail to download them all again.
