### ISSUE TITLE
handler called, but no children ([Errno 10] No child processes)

### ISSUE THREAD

**Issue by triatic** [getmail6/getmail6#182]
I've just installed getmail 6.18.13, obtained via pip, on Ubuntu 23.10.

I have getmail checking for emails on Gmail and Outlook accounts authenticated with xoauth2 (`getmail-gmail-xoauth-tokens`), which executes silently as long as nothing is fetched.

But if one account has emails waiting to be fetched, an error message is emitted when all subsequent accounts are checked:
`handler called, but no children ([Errno 10] No child processes)`

Everything still functions correctly as far as I can see, but I don't want to dump cron output to /dev/null.

**Comment by rpuntaie** [comment]
Could you provide your config? Are there processes involved other than getmail6?

**Comment by triatic** [comment]
I'm calling it via crontab: `4-59/10 * * * * getmail/bin/getmail`

The getmail folder is a python virtual environment.

I have one config file for each account but they all follow the same template:

```
[retriever]
type = SimpleIMAPSSLRetriever
server = imap.gmail.com
username = user@gmail.com
use_xoauth2 = true
password_command = ("getmail/bin/getmail-gmail-xoauth-tokens", ".getmail/user_gmail_com.json")

[destination]
type = Mboxrd
path = /var/mail/user

[options]
delete = true
verbose = 0
```

**Comment by triatic** [comment]
Thank you, changing log level works too.

It's great to have a fetcher with xoauth2 support, confirmed working on both Gmail **and** Outlook. 👍👍
