### ISSUE TITLE
MS365 Shared Mailboxes

### ISSUE THREAD

**Issue by pm-jpodolski** [getmail6/getmail6#192]
Hi,

(Getmail version 6.18.13)

Sorry to raise this as an issue but I was wondering if anyone knows how to have Getmail6 collect mail from an MS365 shared mailbox - everything is working fine and set up using OAUTH2 tokens against several user accounts.
I want to consolidate several separate accounts and change them to share mailboxes and connect each using a single user.

I can't find anywhere this is talked about in the documentation nor through searching online.

Any guidance would be appreciated.

Thanks,

Jeff

**Comment by ykasap** [comment]
Obtain the access token of that single user, and specify the shared mailbox address as the "username" of the getmail config.

```
[retriever]
type = SimpleIMAPSSLRetriever
server = outlook.office365.com
username = sharedmailbox@yourdomainname
use_xoauth2 = True
password_command = ("getmail-gmail-xoauth-tokens", "/path/to/your/token.json")
```

**Comment by pm-jpodolski** [comment]
Thank you - that worked.
