### ISSUE TITLE
Possible mailbox fetching duplication (part 2)

### ISSUE THREAD

**Issue by sebadamus** [getmail6/getmail6#193]
Sorry to come back, might I open the thread again? 

Find something... it started to repeat the duplication behaviour.  In logs it repeats "1/7 (11862 bytes)" each time it is run.
This mailbox is not a big one, about 500 emails, so easy to start and finish, but this behavior repeats on all my mailboxes. 

Each time I run the getmail command (with setlock to ensure not running same script several times) it seems to download exactly the same.  

Seems I am doing somthing that makes getmail to loop somehow, I ran each script each hour, meaning for i.e.:
Script for Mailbox 1 INBOX
Script for Mailbox 1 Sent Mail
(after an hour, crontab schedule runs it again, the idea is to let it run indefinitely so I get an updated copy)

(This is the "INBOX" example, but happens the same with "Sent mail" in a separate script/folder/getmailrc)

The **INBOX getmailrc script** config is:
```
[retriever]
type = SimpleIMAPSSLRetriever
server = imap.gmail.com
port = 993
username = denuncias@one-domain.com
password = ThePassworlding
mailboxes = ("INBOX", )

[destination]
type = Maildir
path = ~/getmail/Maildir/denuncias/INBOX/

[options]
delete = false
read_all = false
message_log = ~/getmail/Maildir/denuncias-INBOX.log
delivered_to = false
received = false
verbose = 2
max_messages_per_session = 5000
to_oldmail_on_each_mail = true
```

Here the running script terminal outlput (each coded enclosed text is one run)
1rst
```
voidnull0@Event5:~/1_Scripts$ /usr/bin/setlock -n ~/.getmail/denuncias-INBOX.lockfile ~/.local/bin/getmail -r ~/.getmail/getmailrc-INBOX_denuncias
getmail version 6.18.14
Copyright (C) 1998-2024 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993:
  [INBOX] msg 1/7 (11862 bytes) from <3KJgsYwgTACsUV-YLWSfHJJVbUaZ.NVVNSL.JVT@gaia.bounces.google.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 2/7 (12509 bytes) not retrieved (seen)
  [INBOX] msg 3/7 (12026 bytes) from <3550sYwgTAPQjk-nalhuWYYkqjpo.ckkcha.Yki@gaia.bounces.google.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 4/7 (8422 bytes) from <a-usergmail.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 5/7 (6260 bytes) from <a-user@gmail.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 6/7 (14223 bytes) from <> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 7/7 (14203 bytes) from <> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  6 messages (66996 bytes) retrieved, 1 skipped
Summary:
Retrieved 6 messages (66996 bytes) from SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993
```
2nd
```
voidnull0@Event5:~/1_Scripts$ /usr/bin/setlock -n ~/.getmail/denuncias-INBOX.lockfile ~/.local/bin/getmail -r ~/.getmail/getmailrc-INBOX_denuncias
getmail version 6.18.14
Copyright (C) 1998-2024 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993:
  [INBOX] msg 1/7 (11862 bytes) from <3KJgsYwgTACsUV-YLWSfHJJVbUaZ.NVVNSL.JVT@gaia.bounces.google.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 2/7 (12509 bytes) not retrieved (seen)
  [INBOX] msg 3/7 (12026 bytes) from <3550sYwgTAPQjk-nalhuWYYkqjpo.ckkcha.Yki@gaia.bounces.google.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 4/7 (8422 bytes) from <a-user@gmail.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 5/7 (6260 bytes) from <a-user@gmail.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 6/7 (14223 bytes) from <> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 7/7 (14203 bytes) from <> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  6 messages (66996 bytes) retrieved, 1 skipped
Summary:
Retrieved 6 messages (66996 bytes) from SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993
```

3rd
```
voidnull0@Event5:~/1_Scripts$ /usr/bin/setlock -n ~/.getmail/denuncias-INBOX.lockfile ~/.local/bin/getmail -r ~/.getmail/getmailrc-INBOX_denuncias
getmail version 6.18.14
Copyright (C) 1998-2024 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993:
  [INBOX] msg 1/7 (11862 bytes) from <3KJgsYwgTACsUV-YLWSfHJJVbUaZ.NVVNSL.JVT@gaia.bounces.google.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 2/7 (12509 bytes) not retrieved (seen)
  [INBOX] msg 3/7 (12026 bytes) from <3550sYwgTAPQjk-nalhuWYYkqjpo.ckkcha.Yki@gaia.bounces.google.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 4/7 (8422 bytes) from <a-user@gmail.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 5/7 (6260 bytes) from <a-user@gmail.com> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 6/7 (14223 bytes) from <> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  [INBOX] msg 7/7 (14203 bytes) from <> delivered to Maildir /home/voidnull0/getmail/Maildir/denuncias/INBOX/
  6 messages (66996 bytes) retrieved, 1 skipped
Summary:
Retrieved 6 messages (66996 bytes) from SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993
```
(etc... repeating each run)

What might I try or check?

Thanks,

**Comment by rpuntaie** [comment]
`-ds,` in the command line would set flag `\SEEN` (just committed `mark_read` or `-R` would do the same, but that is not released yet).

But to find the problem first would be good.

`offered message 5/399 but failed` will not be in the `oldmail-` file.
Why are others not in that file? Maybe you can find out and report here.
Maybe an exception while delivering the email?

**Comment by sebadamus** [comment]
> `-ds,` in the command line would set flag `\SEEN` (just committed `mark_read` or `-R` would do the same, but that is not released yet).
> 
> But to find the problem first would be good.
> 
> `offered message 5/399 but failed` will not be in the `oldmail-` file. Why are others not in that file? Maybe you can find out and report here. Maybe an exception while delivering the email?

Thanks for the response! so... -ds cli option currently works with v6.18.14 I presume, but I prefer to stick to what I have now and diagnose as you suggest.

That error: 
```
Server for SimpleIMAPSSLRetriever:denuncias@one-domain.com@imap.gmail.com:993 is broken; offered message 5/399 but failed to provide it.  Please notify the administrator of the server.  Skipping message...
Retrieval error: failed to retrieve msgid 5/400; server said IMAP error (socket error: EOF occurred in violation of protocol (_ssl.c:2426))
```
...wont be shown in the configured log getmailrc "message_log" file, I think I have to `add message_log_verbose = true`, will try that to all accounts download and reportback errors (please tell if not right) sorry I no expert with getmail, just starting :-(

I tend to think that the error reported to the terminal output is when GMAIL starts to throttle down and limit my connection because of excess downloads, so... then the SSL connection fails someway and getmail might not know what to do (but just un-educated guess here :o)

I have two options I am confused their meaning:

1)
**read_all** ([boolean](https://getmail6.org/configuration.html#parameter-boolean)) — if set, getmail retrieves all available messages. If unset, getmail only retrieves messages it has not seen before. Default: True.

I am using `read_all = false`, because I think/though this option will make getmail just download new mails each time its is ran.  But, does this refers to that on the first run it will download the complete mailbox? or just new mails not opened by the user?  Because What I ment to do is to get a complete copy of the mailbox at first place.

2)
**max_messages_per_session** ([integer](https://getmail6.org/configuration.html#parameter-integer)) — if set, getmail will process a maximum of this number of messages before closing the session with the server. This can be useful if your network or the server is particuarly unreliable. Default: 0, which means not to enable this feature.

I am using `max_messages_per_session = 5000` beacuse I read somewhere it would be better for GMAIL not to kill my connection (but I have ran 2 accounts simultaneously without this option and no problem so far, dont know what if I ran 15 accounts simultaneously as I was doing in my last posts)
So, if I use 5000 in this options, does it means it will download just 5000 messages each time it is ran? so if for i.e. I have 20000 mails, it will take 4 runs to download completely? 
Or that it will download the 20000 mails in one run but it will close the connection and open it again until download all?

**Comment by rpuntaie** [comment]
`-ds,` (the comma needs to be there).

To find the problem, you will have to check the code. Grep for the variable you are interested in.
