### ISSUE TITLE
can't concat str to bytes

### ISSUE THREAD

**Issue by mabod** [getmail6/getmail6#20]
Hi,

I moved from getmail 5 (which I have been using for many years) to getmail6 and I am getting a persistent error which does not allow me top receive emails:

```
2020-08-23 08:25:02 msg  1/47 (92343 bytes) msgid 1373023924/35200 from <SRS0=Fdaj=B6=bounce.mailing.tommy.com=bounce-25102_HTML-119607403-14328906-6407580-1763@mx.myprovider.com>
2020-08-23 08:25:03 Delivery error (mboxrd delivery 73644 error (127, mbox delivery process failed (can't concat str to bytes)))
```

The destination definition in the rc file looks like this:

```
[destination]
type = Mboxrd
path = /home/matthias/mailbox/matthias
```
The destination file does exists, it was used by getmail 5, and is over 100 MB in size.

I did not change any settings, just installed getmail6.

This is on Manjaro testing, with getmail6 package from AUR (version 6.03) and Python 3.8.5.

**Comment by emtiu** [comment]
The code change in #22 fixes the bug in my testing. **Please** make a backup of your mailbox file before trying this out yourself. Even if the fix seems trivial, I don't want to cause any heartache :)

**Comment by mabod** [comment]
Just installed getmail6-git. I can confirm that it works for me now. Thanks.
