### ISSUE TITLE
Microsoft outlook 'modern authentication'

### ISSUE THREAD

**Issue by jkbsc** [getmail6/getmail6#200]
Microsoft have decided to enforce a new approach to authentication, as outlined here: [modern authentication methods now needed](https://support.microsoft.com/en-gb/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d)

From the documentation, I think that getmail6 can already work in a similar way with gmail. Does anyone have plans to make getmail work with MSFT's new approach above?

**Comment by rpuntaie** [comment]
That what `getmail-gmail-xoauth-tokens` is for. There have been issues, like #145. But it should work.

**Comment by jkbsc** [comment]
Thank you for the pointer.  I will close this issue.
