### ISSUE TITLE
App registration on Azure

### ISSUE THREAD

**Issue by xianwenchen** [getmail6/getmail6#201]
Hi!

Outlook is being unreasonable that it does not allow app password access for IMAP!

I have been trying to following example rc No. 13, to set up oauth2 for an Outlook/Live mail address.

I haven't signed up for an Azure account, because I'm concerned with costs.

However, I'm still able to sign into portal.azure.com using my Live mail address.

One problem is that I cannot find Managing Azure Active Directory.

Another problem is that I can find App Registrations, but cannot register a new app. The message was that  *Register an application The ability to create applications outside of a directory has been deprecated. You may get a new directory by joining the M365 Developer Program joining the M365 Developer Program or signing up for Azure.*

Does this mean that I have to properly sign up for an Azure account, before I can register an app within the Azure Active Directory?

After registering, Azure advertises that I will get limited free credits for 30 days, 12 months free popular services, and 65 services always free. Do you know if register an app and using it for oauth2 purpose with getmail6 will be free forever as part of the 65 services, or free for 12 months as a popular service, or only free for 30 days using the limited free credits?

Thank you in advance!

**Comment by emtiu** [comment]
I'm afraid we cannot help you with those questions. getmail6 is a Python script to retrieve email from online mailboxes. You'll need to ask questions about prices on Azure to Microsoft or a forum of their users.

**Comment by xianwenchen** [comment]
Thanks.
