### ISSUE TITLE
Question: What file types are created when downloading mails?

### ISSUE THREAD

**Issue by BananaAcid** [getmail6/getmail6#202]
Hi,

I could not find any info in the docs (maybe I missed it?) to what files are generated when getting the mails.

I would like to know, If and how the mail files could be read later and if they are in a proprietary format.

**Comment by rpuntaie** [comment]
See
https://en.wikipedia.org/wiki/Maildir

if you have

```
[destination]
type=Maildir
```

See https://github.com/getmail6/getmail6/blob/master/getmailcore/destinations.py
for other types, but some of which will also produce Maildir, indirectly.

Maildir: Basically mails as text files instead of in a database.

**Comment by BananaAcid** [comment]
Thanks, this seems, the files can not be opened by outlook or alike for viewing, like with .eml or .msg files.
