### ISSUE TITLE
Inject report to MDA if getmail fails to login

### ISSUE THREAD

**Issue by bilogic** [getmail6/getmail6#213]
Can getmail be configureed to deliver a report to its MDA if it can't login to IMAP/POP3?

This will be helpful without having to keep a lookout for providers changing their login policies.

**Comment by emtiu** [comment]
I do this in a roundabout way: getmail runs from the crontab, and if the getmail command there produces an error, it gets deposited in the the user's mailbox through the system's MDA (which is the same one that getmail calls for delivery).

**Comment by rpuntaie** [comment]
@emtiu Would you share your crontab command?

**Comment by emtiu** [comment]
There's simply a call to `getmail` (without `-v`) in my user's crontab. Without errors, it produces no output. When there's an error, the output of `getmail` gets delivered to the user as mail.

As far as I understand it, the following then happens: The system consults `/etc/aliases`, and this directs the mail to an address understood by `postfix`. Postfix then delivers the mail in much the same way as when getmail fetches mail (it even runs through the same Sieve filters for me).

**Comment by rpuntaie** [comment]
Ah, I understand. It is a [crontab feature](https://askubuntu.com/questions/500749/cron-job-not-running-postfix-sendmail-error) to deliver command errors as mails no matter what the command does.

**Comment by bilogic** [comment]
How about the folks using `--idle=INBOX` and not crontab?

**Comment by rpuntaie** [comment]
I had a look into the code. It is too complicated to implement. I just maintain: fix bugs and add some easy features. 

Maybe a separate script could parse `logfile` (by option) or `message_log_syslog`  (by option) and send mails.

**Comment by rpuntaie** [comment]
Maybe you could do a pull request, though? You would have the context to test it with `--idle` . I'm thinking of a [custom logging handler](https://docs.python.org/3/library/logging.handlers.html) and have  a `message_log_email` similar to `message_log_syslog`.

**Comment by emtiu** [comment]
If the `mail` command is working on your system, you might try something like `getmail | mail root`, but I'm not sure if that waits for `getmail` to exit (can't test right now).
