### ISSUE TITLE
Where to ask questions about options? Discussions?

### ISSUE THREAD

**Issue by sebadamus** [getmail6/getmail6#215]
Hi, I am very sorry to bother here without an issue but a question O:-)

1) is there any active official forum for getmail6 tools? 

2) is it ok to ask here if need help with **read_all (boolean)** option?

3) would it be possible to enable the Github Discussions tab for the repository? (kind of forum stuff, so we users can post doubts, help, experiences...

Thanks,

**Comment by emtiu** [comment]
Hi, Sebastian! For the moment, it's easiest to just post your questions in here. We can just close the Issue once you question has been answered :)
