### ISSUE TITLE
IMAP usage extremely inefficient when not deleting and not synchronizing changes

### ISSUE THREAD

**Issue by SethRobertson** [getmail6/getmail6#219]
I have a conceptually simple configuration: there is an imap mail server that I am trying to download/mirror.   However, the real user of the mail account still needs access to the mail on the imap server and will use whatever deletion policy they want, including never deleting emails.  This can yield extremely large numbers of emails on the server.

Whenever getmail decides to look at the mail server, it downloads the complete list of messages and then decides whether it wants to grab them.  But this process of downloading the messages can take many minutes and results in large volumes of useless network traffic.  In this use case, we don't actually want/need to synchronize flags or seen or changes or whatever.  Just grab unseen emails.

If I am to believe stackoverflow (https://stackoverflow.com/questions/1084780/getting-only-new-mail-from-an-imap-server) this is a use case that imap supports.  Basically cache the last UID and the UIDVALIDITY and instead of starting from message 1 every time, start from the last obtained UID.

**Comment by rpuntaie** [comment]
I merged and close this now. Thanks a lot.
