### ISSUE TITLE
getmail-gmail-xoauth-tokens: AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by mabod** [getmail6/getmail6#23]
In order to retrieve emails from google the XOAUTH2 protocol needs to be setup. This was working for me with getmail5 but not with getmail6 anymore.

I tried to setup it up from scratch following this tutorial: https://www.bytereef.org/howto/oauth2/getmail.html
But it is not working.

The `gmail.json` file I am using:

```
{"scope": "https://mail.google.com/",
 "user": "my-google-user@gmail.com",
 "client_id": "new-client-id-created-for-getmail6",
 "client_secret": "new-secret-coming-with-new-client-id",
 "token_uri": "https://accounts.google.com/o/oauth2/token",
 "auth_uri": "https://accounts.google.com/o/oauth2/auth",
 "redirect_uri": "urn:ietf:wg:oauth:2.0:oob",
 "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"}

```
The output of `getmail-gmail-xoauth-tokens --init gmail.json` :  

```
Visit this url to obtain a verification code:
Traceback (most recent call last):
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 110, in <module>
    print("    %s\n" % auth.code_url())
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 57, in code_url
    return '%s?%s' % (self.data['auth_uri'], self.query(params))
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 49, in query
    for param in sorted(params.iteritems(), key=lambda x: x[0]):
AttributeError: 'dict' object has no attribute 'iteritems'
```

This is with Manjaro testing, newest getmail 6.4  and Python 3.8.5

These are the XOAUTH2 instructions from google: 

https://developers.google.com/identity/protocols/oauth2/native-app

Following the link to the "Credentials Page" to create a new client id + secret for getmail6

**Comment by rpuntaie** [comment]
Please report whether it works now.

**Comment by rpuntaie** [comment]
Urllib was still not compatible. Could you try now?

**Comment by mabod** [comment]
I am one step further now. `getmail-gmail-xoauth-tokens` gives me the url where I can find the verification code but instead of waiting for me to enter the code it throws this error:

```
Traceback (most recent call last):
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 117, in <module>
    code = raw_input("Enter verification code: ")
NameError: name 'raw_input' is not defined
```

**Comment by mabod** [comment]
We are one step further. I can enter the verification code but then this error occurs:

```
Enter verification code: xxxxxxxx
Traceback (most recent call last):
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 119, in <module>
    response = auth.init_tokens(code)
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 87, in init_tokens
    d = self.get_response(self.data['token_uri'], params)
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 67, in get_response
    response = urlrequest.urlopen(url, encoded).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 522, in open
    req = meth(req)
  File "/usr/lib/python3.8/urllib/request.py", line 1281, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

```

**Comment by mabod** [comment]
The fix is not sufficient. After enetring the verification code it now gives:

```
Enter verification code: xxxxx
Traceback (most recent call last):
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 119, in <module>
    response = auth.init_tokens(code)
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 87, in init_tokens
    d = self.get_response(self.data['token_uri'], params)
  File "/usr/bin/getmail-gmail-xoauth-tokens", line 67, in get_response
    response = urllibrequest.urlopen(url, encoded).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

```

**Comment by mabod** [comment]
My mistake. It works. In my last test I used the wrong verification code. With the correct verification code getmail-gmail-xoauth-tokens completes the job. And getmail6 is now retrieving emails from gmail. All is good!


By the way, in order to make getmail authenticate via the xoauth token the `[retriever]` section needs to be properly setup:

```
[retriever]
type = SimpleIMAPSSLRetriever
use_xoauth2 = True
server = imap.gmail.com
username = your-gmail-user@gmail.com
password_command = ("getmail-gmail-xoauth-tokens", "/path-to-your-users-getmail-directory/gmail.json")
```

**Comment by mabod** [comment]
With that said I am closing this issue.

**Comment by rpuntaie** [comment]
Python 3 `urlopen` throws an exception, while Python 2 has the `Bad Request` in the response object.

**Comment by emtiu** [comment]
> By the way, in order to make getmail authenticate via the xoauth token the `[retriever]` section needs to be properly setup:
> ```
> [retriever]
> type = SimpleIMAPSSLRetriever
> use_xoauth2 = True
> server = imap.gmail.com
> username = your-gmail-user@gmail.com
> password_command = ("getmail-gmail-xoauth-tokens", "/path-to-your-users-getmail-directory/gmail.json")
> ```

Is this represented correctly in the current documentation? If not, you can open another issue so we can fix it.

**Comment by mabod** [comment]
The `password_command` or  `use_xoauth2` variables are not mentioned in  the documentation at all.

**Comment by rpuntaie** [comment]
They are: in configuration.html.
I've added this example to `docs/getmailrc-examamples`.
