### ISSUE TITLE
Auto generate .txt files from .html and lock as readonly, or eliminate altogether

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#32]
Apparently the .html and .txt files are indeed being maintained by hand separately.
I recommend using
`$ w3m -dump file.html > file.txt`

Therefore please make the .txt files in this repository read-only,
with a warning at top "Do not edit, created automatically from HTML version."

Sure, one could say "just have setup.py create the .txt files." But the user might not have w3m etc. installed.
So still distribute them.

Or, just consider not maintaining .txt files at all.

**Comment by rpuntaie** [comment]
I added a Makefile today, which uses `links`.
That produced the `.txt` that was there (`lynx` probably would have, too).

**Comment by jidanni** [comment]
OK but if I go to https://github.com/getmail6/getmail6/blob/master/docs/documentation.txt
I can still press the edit button.

One can imagine a user spending hours editing this, only to find he should have edited the HTML version.
Therefore it should be configured to be readonly, here on GitHub.

**Comment by rpuntaie** [comment]
I know the situation with redundant text is no good, but I don't want to change too much.

- Read-only would not allow to run the Makefile.
- Not including generated files would break existing distro packages.

With the `Makefile` at least it is easier to find out that the `.html` is the master and the `.txt` is generated, and how.
I had found only a hint in the CHANGELOG and had to guess how it was generated.

**Comment by Remmy** [comment]
I used a pre-commit hook in git to do something similar to above every time one of the html files gets updated and committed to git.

**Comment by jidanni** [comment]
> I used a pre-commit hook in git to do something similar to above every time one of the html files gets updated and committed to git.

OK. Maybe also have that hook put
`"Warning, do not edit this .txt file which is automatically produced from the .html version"`
at the top of each automatically produced .txt file.
