### ISSUE TITLE
Call for Debian getmail6 maintainer

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#33]
I'm putting this [call for a Debian getmail6 package maintainer](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969021) here in this GitHub issue tracker, in the hopes that someone will see it one day and step forth an be the maintainer.

**Comment by Remmy** [comment]
I don't think this is the appropiate place for having this request as we don't want to have open issues for every OS or distribution not having getmail6 pre packaged. The proper place, IMHO, is on the distro's mailinglist and/or bug tracker as you've done.

Perhaps we can include in the documentation links to https://repology.org/project/getmail/versions and https://repology.org/project/getmail6/versions ?

**Comment by jidanni** [comment]
You are right about this being the wrong place, and there is hope, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969021#13 . So I'll close this.
