### ISSUE TITLE
Document how to upgrade getmail6

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#36]
The user successfully installs getmail6.
But sooner or later it comes time to upgrade to a new release.
OK, once #12 is finished, he will know how to remove getmail6, so he can install the new version from scracth.
However, maybe it is possible to "upgrade in place" without removing the old version of getmail6.
Please document how.
Yes, many users will be using e.g., Debian, where they can just do "apt-get upgrade". But before this is possible, it would still be best to document how users could upgrade getmail6 manually themselves.

**Comment by rpuntaie** [comment]
Basically one needs to look into the setup.py file and manually the files from the system listed there.

But I've made getmail6 a pypi package now. So

```
pip uninstall getmail6
``` 

will uninstall, if it was installed with

```
pip install getmail6
```

I also added this to the README and documentation.
