### ISSUE TITLE
Version blurb should start mentioning others and keep year fresh

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#37]
When running we see
```
getmail version 6.4
Copyright (C) 1998-2019 Charles Cazabon.  Licensed under the GNU GPL version 2.
```

Maybe this should start saying
Copyright (C) 1998-20**20** Charles Cazabon **and others**.  Licensed under the GNU GPL version 2.

**Comment by jidanni** [comment]
Man page says too
```

REPORTING BUGS
       Report bugs to <charlesc-getmail-bugs@pyropus.ca>.
```

**Comment by emtiu** [comment]
There's a couple more places that (so far) only have Charles Cazabon's name: https://github.com/getmail6/getmail6/search?q=charles&unscoped_q=charles

Of course the main credit for this software should be his. At the same time, it would be fair to show that he's not the main person responsible for the code shipped as getmail6.
