### ISSUE TITLE
"Return-Path: <unknown>" can confuse MTAs/LDAs down the line

### ISSUE THREAD

**Issue by emtiu** [getmail6/getmail6#38]
As any MTA should, getmail writes a `Return-Path` header to every message. It writes `Return-Path: <unknown>` if it cannot find an appropriate sender address.

I use getmail's `MDA_external` destination to pass messages to `dovecot-lda` for final delivery. If a message contains `Return-Path: <unknown>` (which, surprisingly, is the case for something like 30–50% of my mail), this understandably irritates dovecot-lda into logging `Warning: Failed to parse return-path header`.

I really want to silence this warning, which is spamming my logs. Currently, I'm employing an ugly hack:

- passing `arguments = ('-f', 'invalid@invalid.invalid')` to dovecot-lda, thereby overriding getmail's Return-Path with a lexically valid (but nonsensical) address

That's ugly and painful to configure (because I maintain a large number of `getmailrc` files). There's a another potential solution, but that would require changing the behavior of dovecot-lda:

- calling dovecot-lda with the `-e` option (which is the way I am doing it) means it will never send bounces, and instead just fail with some stderr output if a message cannot be delivered. In this case, the content of the Return-Path header is irrelevant. dovecot-lda could arguably ignore the Return-Path header when called with `-e`, and just never attempt to parse it—silencing the warning.

However, it seems unlikely that this corner-case will warrant a change to dovecot, which is a very large project. In my mind, there's more of a chance to change getmail ;) But how?

- I've taken a good look at the possibility of adding a new global option like `return_path = False`. It could prevent modifying or adding any Return-Path header, and especially `Return-Path: <unknown>`. However, judging from the way `delivered_to` is implemented (which does nearly the same thing), this would require major code changes. These could cause breakage with some of the more exotic usecases for getmail (like multidrop retrieval), which we're not equipped to adequately test.

- Maybe instead of `<unknown>`, getmail could write something lexically valid but nonsensical like `invalid@invalid.invalid`? This would prevent tripping up MTAs/LDAs down the line, as happens in my case. However, if bounce mails were really dispatched to this address, even more error spam would ensue, so that probably shouldn't be a default.

I'm curious if anyone has an opinion or idea about this :)

**Comment by rpuntaie** [comment]
Might that wrong case have been the reason for the many `<unknown>` you observed?

**Comment by emtiu** [comment]
No, that can't be it. It took me forever to figure this out, but here goes:

getmail's Message class derives from Python's `email.Message` class (as instantiated by `email.parser` in message.py). Its [documentation says](https://docs.python.org/3/library/email.message.html) (emphasis mine):
> The EmailMessage dictionary-like interface is indexed by the header names, which must be ASCII values. The values of the dictionary are strings with some extra methods. Headers are stored and returned in case-preserving form, but **_field names are matched case-insensitively_**.

I've verfied this to be the case in a debugger session:
```
(Pdb) self._Message__msg['return-path']
'<xxx@yyy.de>'
(Pdb) self._Message__msg['Return-Path']
'<xxx@yyy.de>'
```

So the change in 07f831f8230ad07b88e4cd8a535c70ded4c179cb should have no effect at all.

I'm thinking getmail's way of determining of a proper value for `Return-Path` when parsing a message is just too limited. Consider this excerpt from the headers of a message delivered through getmail6:
```
Return-Path: <unknown>
Received: from […]
Subject: […]
From: xxx-bounces@lists.yyy.de
Date: Mon, 14 Sep 2020 20:35:15 +0200
Errors-To: xxx-bounces@lists.yyy.de
Sender: "XXX" <xxx-bounces@lists.yyy.de>
```

It seems weird for getmail to set `Return-Path: <unknown>` when the message also contained both `Sender` and `Errors-To` headers. But judging from the code, only `Return-Path` and no other header is considered in incoming messages:

https://github.com/getmail6/getmail6/blob/07f831f8230ad07b88e4cd8a535c70ded4c179cb/getmailcore/message.py#L130-L133

This probably relates to the expectation that _every_ MTA should do exactly this, as laid out in the documentation:

https://github.com/getmail6/getmail6/blob/07f831f8230ad07b88e4cd8a535c70ded4c179cb/docs/faq.txt#L579-L581

So, getmail probably relies on other MTAs being well-behaved and always setting a `Return-Path`, which apparently is not the reality.

**What might getmail do instead?** In the example message above, the value of `Errors-To` is a sensible choice to use for `Return-Path`. `Sender` might also be under certain circumstances, and probably more. But I don't know nearly enough about the standards and practices of the email protocol to suggest a decent set of headers to consider.

**Comment by rpuntaie** [comment]
07f831f8230ad07b88e4cd8a535c70ded4c179cb is still good for consistency.

`Errors-To` I would not use, because we just retrieve and don't send mails.
`Sender` seem good to me to default to before `unknown`.

**Comment by emtiu** [comment]
As I understand it, the point of `Return-Path` is to provide an answer to: Where should the bounce go if this message fails to deliver? So `Errors-To` would make sense in my mind. But for the time being, I'll give the new `Sender` default a spin sometime after the next release, and see if that reduces the incidence of `Return-Path: <unknown>`. Thanks!

**Comment by rpuntaie** [comment]
The fact, that there are more names for bouncing addresses, tells me that bouncing is considered general. There can be more reasons for bounces. Errors are one reason.
`Return-Path` is general, too: the way where the mail came from, but backward, i.e. back to sender.
`Errors-To` on the other hand is more specific for error bounces.

Some links:
https://en.wikipedia.org/wiki/Bounce_address (only one mentioning `Errors-To`)
https://en.wikipedia.org/wiki/Bounce_message
https://tools.ietf.org/html/rfc2822
https://tools.ietf.org/html/rfc3834
