### ISSUE TITLE
gnomekeyring functionality broken

### ISSUE THREAD

**Issue by brianmay** [getmail6/getmail6#43]
Looks like gnomekeyring has been removed and is no longer available.

This project shoulod be updated to use keyring instead. https://pypi.org/project/keyring/

**Comment by rpuntaie** [comment]
`gnomekeyring` was removed from what?

I use [pass](https://www.passwordstore.org/), so I've never tried this feature of getmail6.

I've looked into the keyring package. It works for all platforms. It can replace also getmail6's OSX keychain code.
But ``--store-password-in-gnome-keyring`` should then better be ``--store-password-in-keyring``, which is an interface change.
Anybody any problem with that?

**Comment by brianmay** [comment]
I don't care. This is fine with me.

Maybe better, fewer characters to type :-)

I probably should investigate pass again sometime too. But not sure how you would use pass with getmail...

**Comment by Remmy** [comment]
I have no problem with it, but, (also depending on how many people use it), would it be possible to have both work, and only document the new one? Then maybe print a warning for the old form being deprecated and removed in a future version?

**Comment by rpuntaie** [comment]
[gnomekeyring](https://packages.debian.org/stretch/python-gnomekeyring) is in debian `jessie` and `stretch`, then dropped.

@Remmy Yes. I'll do that.
