### ISSUE TITLE
AttributeError: module 'getmailcore.destinations' has no attribute 'SimpleIMAPSSLRetriever'

### ISSUE THREAD

**Issue by law** [getmail6/getmail6#46]
Cannot run getmail on openbsd 6.8, installed locally via OS's 'pip', without getting the above error.  My config file looks like: 

```
$ cat ~/.getmail/getmailrc 
[retriever]
type = SimpleIMAPSSLRetriever
server = old.imap.server
username = law@olddomain
password = xxx
mailboxes = ALL

[destination]
type = SimpleIMAPSSLRetriever
server = new.imap.server
username = law@newdomain
password = xxx

[options]
read_all = False
```

```
$ ~/.local/bin/getmail -v

Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.8
  Python version 3.8.6 (default, Oct 13 2020, 09:04:17) 
[Clang 10.0.1 ]

Unhandled exception follows:
    File "/home/law/.local/bin/getmail", line 773, in main
    destination_func = getattr(destinations, destination_type)
  AttributeError: module 'getmailcore.destinations' has no attribute 'SimpleIMAPSSLRetriever'

Please also include configuration information from running getmail
with your normal options plus "--dump".
```

**Comment by Remmy** [comment]
Hi Lee, you can not use [destination] for a second mail account. If you want to pull mail from a second account, you could create a second .getmailrc file (for example .getmailrc-newimap) and set the credentials in the retriever section of that file. You can then use "getmail -r .getmailrc-newimap" to put that account.

Or are you trying to copy mail from your old account to your new one?

Anyways, have a look at how to use the retriever and destinations sections in the manual: 
https://getmail6.org/configuration.html#conf-retriever
https://getmail6.org/configuration.html#conf-destination

**Comment by law** [comment]
Ah, fair enough, that makes a ton of sense!  Thanks so much for the quick reply.  Would adding remote IMAP handling to the 'retriever' section be a suitable feature request for this project?  If so, I'd be happy to close this ticket and create a feature-request one.

**Comment by rpuntaie** [comment]
There is IMAP handling. Your `[retriever]` does set up IMAP and it seems OK.
Just your `[destination]` is not OK. It could be

```
[destination]
type = Maildir
path = ~/Mail/<your_email_here>/INBOX/
```
