### ISSUE TITLE
Unhandled exception, UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1031: invalid start byte

### ISSUE THREAD

**Issue by beckflorian** [getmail6/getmail6#49]
Hello everyone...

I am calling getmail from IMAP Grab 0.1.4 on Raspian jessie and get the following error:
===================================
Downloading mailbox "Gesendet"

Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.10
  Python version 3.4.2 (default, Sep 16 2019, 19:58:00)
[GCC 4.9.2]

Unhandled exception follows:
    File "/usr/local/bin/getmail", line 809, in main
    destination = destination_func(**destination_args)
    File "/usr/local/lib/python3.4/dist-packages/getmailcore/destinations.py", line 86, in __init__
    ConfigurableBase.__init__(self, **args)
    File "/usr/local/lib/python3.4/dist-packages/getmailcore/baseclasses.py", line 356, in __init__
    self.checkconf()
    File "/usr/local/lib/python3.4/dist-packages/getmailcore/baseclasses.py", line 365, in checkconf
    self.conf[item.name] = item.validate(self.conf)
    File "/usr/local/lib/python3.4/dist-packages/getmailcore/baseclasses.py", line 307, in validate
    first_line = f.readline()
    File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1871: invalid start byte

ocbak@hugo:~ $ getmail --dump
Error: Default config/data dir "/share/ocbak/.getmail/" does not exist - create or specify alternate directory with --getmaildir option

=====================================

It happens only in 2 of 20 mail folders. 
Is this an Issue of IMAP Grab, getmail or Python itself?

What can I do?

Thanks a lot

**Comment by rpuntaie** [comment]
It is a getmail issue.

I've made this yet untested fix:
https://github.com/getmail6/getmail6/commit/26320aa7a22e6483bdf73615e07008a3a1b2c270

Would you test it?

**Comment by libnoon** [comment]
I use getmail with mbox.  6.9 worked correctly, but master does not work:

```
  getmail version 6.11
  Python version 3.9.1rc1 (default, Nov 27 2020, 19:38:39) 
[GCC 10.2.0]

Unhandled exception follows:
    File "/home/noon/git/getmail6/getmail", line 813, in main
    destination = destination_func(**destination_args)
    File "/home/noon/git/getmail6/getmailcore/destinations.py", line 86, in __init__
    ConfigurableBase.__init__(self, **args)
    File "/home/noon/git/getmail6/getmailcore/baseclasses.py", line 350, in __init__
    self.checkconf()
    File "/home/noon/git/getmail6/getmailcore/baseclasses.py", line 359, in checkconf
    self.conf[item.name] = item.validate(self.conf)
    File "/home/noon/git/getmail6/getmailcore/baseclasses.py", line 301, in validate
    status_old, f = f_mbox(val)
  NameError: name 'f_mbox' is not defined
```

**Comment by rpuntaie** [comment]
Thanks. If `__all__` is there Python does not look beyond and I didn't think of that. I could have tested this even if not using mbox myself.

The mbox problem here is with Unicode chars. So if you didn't have any in your mails, it did not surface.
It should work again. Please try. Testing is all.

**Comment by rpuntaie** [comment]
@libnoon or @beckflorian If you give me a short feedback, whether mbox works, I close this and make a release today.

**Comment by libnoon** [comment]
I'm afraid that is not all.  Last time I checked, the lock handling code is incorrect with your change.  I'll try to make a contribution to fix it...

**Comment by rpuntaie** [comment]
I wanted to reduce code repetition, but I could have fixed this with a one char change. Maybe we should do that, then.

**Comment by libnoon** [comment]
I've started to review/rework the locking code but it looks like it's a rather large endeavour...

**Comment by rpuntaie** [comment]
Thanks, but I better undo the f_mbox function and just change the offending code.

**Comment by rpuntaie** [comment]
@libnoon if you could verify this latest change I would close this

**Comment by libnoon** [comment]
@rpuntaie it works on my side.  Thanks!
