### ISSUE TITLE
getmail seems to lose its child process and hangs forever

### ISSUE THREAD

**Issue by ykasap** [getmail6/getmail6#52]
While retrieving messages from an IMAP server, getmail sometimes loses track of the child process (in my case /usr/local/lib/mailagent/filter), and hangs forever.  

I'm using getmail 6.11 on FreeBSD 12-STABLE (installed via Ports Collection).  
Here is my configuration.  I'm using OAuth 2.0 for Exchange Online, but I believe it is irrelevant for this problem.

```
% getmail --dump
getmail version 6.11
Copyright (C) 1998-2020 Charles Cazabon and others. Licensed under GNU GPL version 2.
getmail configuration:
  getmail version 6.11
  Python version 3.7.9 (default, Oct 17 2020, 01:23:59) 
[Clang 8.0.1 (tags/RELEASE_801/final 366581)]
  retriever:  SimpleIMAPSSLRetriever(ca_certs="None", certfile="None", getmaildir="/home/kasahara/.getmail", keyfile="None", mailboxes="('INBOX',)", move_on_delete="None", password="*", password_command="('getmail-gmail-xoauth-tokens', '/home/kasahara/.getmail/exchange.json')", port="993", record_mailbox="True", server="outlook.office365.com", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_cram_md5="False", use_kerberos="False", use_peek="True", use_xoauth2="True", username="email@domainname")
  destination:  MDA_external(allow_root_commands="False", arguments="()", command="filter", group="None", ignore_stderr="False", path="/usr/local/lib/mailagent/filter", unixfrom="True", user="None")
  options:
    delete : False
    delete_after : 0
    delete_bigger_than : 0
    delivered_to : False
    fingerprint : False
    logfile : logfile(filename="~/.getmail/getmail.log")
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : ~/.getmail/getmail.log
    message_log_syslog : False
    message_log_verbose : False
    read_all : False
    received : True
    verbose : 0

% cat getmailrc
[retriever]
type = SimpleIMAPSSLRetriever
server = outlook.office365.com
username = email@domainname
use_xoauth2 = True
password_command = ("getmail-gmail-xoauth-tokens", "/home/kasahara/.getmail/exchange.json")

[destination]
type = MDA_external

path = /usr/local/lib/mailagent/filter
unixfrom = true

[options]
verbose = 0
read_all = false
delete = false
delete_after = 0
delete_bigger_than = 0
max_bytes_per_session = 0
max_message_size = 0
max_messages_per_session = 0
delivered_to = false
received = true
message_log = ~/.getmail/getmail.log
message_log_syslog = false
message_log_verbose = false
```

I tried getmail --trace and got the following output.

Normal case:
```
...(omit)
deliver_message() [destinations.py:107] trace
_deliver_message() [destinations.py:644] trace
msginfo "{'sender': 'someone@somedomain'}"
_prepare_child() [baseclasses.py:416] 
spawned child 67316
_wait_for_child() [baseclasses.py:426] waiting for child 67316_child_handler() [baseclasses.py:400] handler called for signal 20_child_handler() [baseclasses.py:410] handler reaped child 67316 with status 0
command filter 67316 exited 0
    delivered to MDA_external command filter (b"about to execl() with args ['/usr/local/lib/mailagent/filter', '/usr/local/lib/mailagent/filter']")
  msg 8078/8125 (93434 bytes) delivered
....(omit)
```
Blocked case:
```
...(omit)
deliver_message() [destinations.py:107] trace
_deliver_message() [destinations.py:644] trace
msginfo "{'sender': 'someone@somedomain'}"
_prepare_child() [baseclasses.py:416] 
spawned child 76563
_wait_for_child() [baseclasses.py:426] waiting for child 76563_child_handler() [baseclasses.py:400] handler called for signal 20_child_handler() [baseclasses.py:410] handler reaped child 76563 with status 0_wait_for_child() [baseclasses.py:426] waiting for child 76563_wait_for_child() [baseclasses.py:426] waiting for child 76563_wait_for_child() 
(repeated indefinitely)
```

When I killed the blocked getmail process and invoked again, I got a duplicate message, so I believe that the external filter program was successfully called and the message was delivered locally, but getmail couldn't detect it.  I have no idea if the problem is in Python, getmail6, or FreeBSD....  I tried to call /usr/sbin/sendmail (with options needed) instead of mailagent's filter program, but the same problem occured. 

Is it possible to let getmail spawn the external filter, immediately forget about it, and proceed to the next message (maybe with a configurable delay) ?  I think getmail doesn't need to wait until mailagent's filter is finished.  It handles locking by itself, and it also tries to go into daemon state. It is fine to invoke multiple 'filter' simultaneously.

**Comment by emtiu** [comment]
Hi, I'm the port maintainer for getmail6 on FreeBSD. Thanks for your report! I've been using getmail6 on FreeBSD 11.x since it came out, and good old getmail for a number of years before that, always with MDA_external (in my case maildrop from postfix, never sendmail from the FreeBSD base system). I haven't seen this problem before.

My first suggestion would be to try and call filter (and/or sendmail) from the console independently of getmail6, and try to feed it a message that you know has caused this problem via shell piping. Maybe there's some output from filter/sendmail that getmail6 isn't showing you, and that could explain the problem.

**Comment by ykasap** [comment]
Thank you very much for the reply.  The problem is not message specific.  Whenever I restart getmail6, it re-fetches the same message from the IMAP server and almost always delivers it without problem.... and then stucks again on another message (sometimes).  I suspect a race condition, because it happens sporadically.

My environment:
% uname -a
FreeBSD (hostname) 12.2-STABLE FreeBSD 12.2-STABLE r368688 ELVENBOW  amd64

Once I wrapped 'filter' with a shell script to redirect the stdout/stderr to a file while the problem occured, but no message was recorded.

I'm using sendmail from base system and mail/mailagent for 20 years on FreeBSD, and they work pretty well when getmail6 is not involved.  The log of 'filter' says like this only when called from getmail6:
```
20/12/21 18:20:42 filter[56630]: SYSERR ioctl: Operation not permitted (1)
20/12/21 18:20:42 filter[56630]: WARNING could not release tty control
```
but it is not linked with the symptom.  The source comment of this part says this warning is harmless.  There might be something incompatible with how getmail6 spawns a child process, but I don't have enough knowledge to understand what is happening.

Here is some FreeBSD specific information about a stucked getmail process:
ps lww $[pid}
```
 UID   PID PPID C PRI NI   VSZ   RSS MWCHAN STAT TT     TIME COMMAND
1001 32721 5031 4  25  5 36996 24544 usem   SN    -  0:02.31 /usr/local/bin/python3.7 /usr/local/bin/getmail
```
procstat -kk ${pid}
```
  PID    TID COMM                TDNAME              KSTACK                       
32721 101692 python3.7           -                   mi_switch+0xd4 sleepq_catch_signals+0x403 sleepq_timedwait_sig+0x14 _sleep+0x1b3 umtxq_sleep+0x132 do_sem2_wait+0x6ca __umtx_op_sem2_wait+0x76 amd64_syscall+0x387 fast_syscall_common+0xf8 
```
I also recorded ps dax, but there was no child process of getmail, and no 'filter' process elsewhere (it seemed to finish local delivery and terminate, because I collected these data when getmail6 didn't terminate after 120 seconds).

```
 5031  1- SN       0:00.76 |-- /bin/sh - /home/kasahara/bin/getmail-idle.sh
32721  -  SN       0:02.31 | |-- /usr/local/bin/python3.7 /usr/local/bin/getmail
32762  -  RN       0:00.00 | |-- ps dax
32763  -  SN       0:00.01 | `-- mail -s getmail [32721] seems stucked...killed kasahara
```

I have little experience with python.  I tried to build python37 with DEBUG option on FreeBSD but gdb didn't give me python backtrace with py-bt (it always say "unable to read python frame information"), so I couldn't track the bug further.  Any suggestion?

**Comment by ykasap** [comment]
I forgot to mention that this is my first try to use getmail, so I have no information if getmail5 has a similar problem or not.

**Comment by rpuntaie** [comment]
It would be interesting to know, whether with getmail5 you had the same problems. Maybe you can try. Anyway, since you experience the problem your help is a chance for getmail6 to overcome it. Maybe you can put some `print('xyz')` into `forkchild()` or `_filter_command()`. I would like to help, but it is hard without the reproducible problem to guide me. Trial and error code changes could help surface the cause on your side.

**Comment by ykasap** [comment]
Thank you for your reply.  I'm trying getmail5 now to narrow down the problem.  I need a couple of more days to see.  I'm not sure if I can find the root cause of hang with Python3...

**Comment by ykasap** [comment]
I cannot reproduce the problem with getmail5/Python 2.7.18 so far.  I'm considering to try getmail6 without the fix of #39 to see if it is related.

**Comment by rpuntaie** [comment]
There was once a `raise` to forget about the child commented out already in getmail 5 (line 427 of `baseclasses.py`).
It somehow makes sense to me to care about one's children.
I would say we should tackle the cause for the hang of your filter process instead.

Your filter hangs with getmail6, but not with getmail5.
The temporary files by which the message is handed over to the filter program might be a little different.
This is because Python 3 does formatting a little differently.

So how to investigate why your filter program hangs?
Here is a suggestion:
In `_pipemail()` you could make an additional file for each message.
Remember the filename in a global list and
print the file name when the wait loops in `_wait_for_child()`.
Then use that file directly with your mail filter program to further investigate.

**Comment by ykasap** [comment]
As far as I observed my filter didn't hang.  It delivered the retrieved message and exited normally.  I had recorded the output of 'ps' during the hang multiple times and there was no 'filter' process remained.  I guess that somehow getmail6 didn't catch it and waited for the lost child forever.

**Comment by emtiu** [comment]
Hi, there! Thanks for your patience and detailed analysis.

Can you check the exit code of your `filter` executable? Maybe it's something different from 0 sometimes, even if a message was delivered, and this could be upsetting getmail6.

**Comment by ykasap** [comment]
I believe the exit status of the child process is 0 even when blocked because `getmail --trace` showed as follows:
`_child_handler() [baseclasses.py:410] handler reaped child 76563 with status 0`

I'm testing getmail6 without the fix of #39 now.

**Comment by ykasap** [comment]
I don't fully understand the fix of #39 yet, but I guess that `_child_handler()` noticed the termination of the child (because it said `"handler reaped child"`), but `_wait_for_child()` was not informed about that.  What happens if the child process exited before `_wait_for_child()` acquires `self.__child_exited` ?

Mailagent's `filter` is very lightweight.  It just puts the injected message to a queue directory as a file, and spawns the main message-filtering program `mailagent` as a background process and exit.

**Comment by rpuntaie** [comment]
Sorry, I missed your intention to show by your `ps` posting that your filter did not hang.

I agree that the #39 change might leak children.
To wait 1 sec, as it was before, is a no go, though.
We need to improve the #39 solution, instead.

The `wait()` doc says *Wait for completion of "a" child process*.
Could it be that by simultaneously exiting children one does not get counted?
I made an experimental change with the more specific `waitpid()`.
Please try.

**Comment by ykasap** [comment]
Thank you for the experimental patch.  I have just installed it.  Please give me a few days to see.

**Comment by emtiu** [comment]
I've tested the patch: In my setup, it doesn't seem to introduce any problems, and works as expected when fetching multiple messages.

**Comment by ykasap** [comment]
I'm afraid that the problem still occured.  I'll try to insert many debug prints to see what is happening when I have time.

**Comment by ykasap** [comment]
I inserted debug probes (rather blindly) like this: https://github.com/getmail6/getmail6/compare/master...ykasap:debughang

I logged perf_counter_ns to make sure that the order of debug outputs are not reversed.  Here is a test output *without* hang.
```
% getmail
2020-12-29 16:50:18 715040098784036 forkchild: forking
2020-12-29 16:50:18 715040100065883 forkchild(85535): forked, calling _prepare_child
2020-12-29 16:50:18 715040100972751 _prepare_child(85535): entered
2020-12-29 16:50:18 715040101038517 forkchild(0): forked, calling _prepare_child
2020-12-29 16:50:18 715040101339833 _prepare_child(85535): exiting
2020-12-29 16:50:18 715040101383352 forkchild(parent): spawned child 85535
2020-12-29 16:50:18 715040101408511 forkchild(parent): calling _wait_for_child
2020-12-29 16:50:18 715040101449449 _wait_for_child: acquiring __child_exited
2020-12-29 16:50:18 715040101475001 _wait_for_child: acquired __child_exited
2020-12-29 16:50:18 715040101496776 _wait_for_child: entering waiting loop
2020-12-29 16:50:18 715040101802117 _prepare_child(0): entered
2020-12-29 16:50:18 715040102092745 _prepare_child(0): exiting
2020-12-29 16:50:18 715040102122845 forkchild(child): calling childfun
2020-12-29 16:50:18 715040133697485 _child_handler: called for signal 20
2020-12-29 16:50:18 715040133751060 _child_handler: os.waitpid
2020-12-29 16:50:18 715040133795201 _child_handler: os.waitpid done
2020-12-29 16:50:18 715040133819776 _child_hander: signal.signal
2020-12-29 16:50:18 715040134093394 _child_handler: reaped child 85535 with status 0
2020-12-29 16:50:18 715040134126013 _child_handler.notify: acquire
2020-12-29 16:50:18 715040134151879 _child_handler.notify: notify_all
2020-12-29 16:50:18 715040134202671 _child_handler.notify: release
2020-12-29 16:50:18 715040134226677 _child_handler.notify: exiting
2020-12-29 16:50:18 715040134256626 _wait_for_child: releasing __child_exited
2020-12-29 16:50:18 715040134279028 _wait_for_child: released __child_exited
```

I wonder why `_prepare_child` is called from both the parent and child, so I added childpid running `_prepare_child`.  Anyway I'll investigate more closely after I got a sample.  Please tell me if you want to add something in a debug output.

**Comment by ykasap** [comment]
Umm, I got a sample, but there seems no difference in the order of events between a blocked case and normal case...  This test code didn't include https://github.com/getmail6/getmail6/commit/7b8066f75e8d3b50326c3a9bf1dcb0b976ace6df.  I'll try again with it.

I noticed that there was only one `_prepare_child()` call recorded (from children??).  I'm starting `getmail6` inside a shell script with `getmail >>$HOME/.getmail/getmail.out 2>&1 &` to collect output and kill after `sleep 120`, but I don't understand the change of behavior. Some output might be lost. In the previous post, I collected output calling `getmail` from my shell.   Anyway...

Normal:
```
2020-12-30 08:01:09 769690364231861 forkchild: forking
2020-12-30 08:01:09 769690365353279 forkchild(93043): forked, calling _prepare_child
2020-12-30 08:01:09 769690366210386 _prepare_child(93043): entered
2020-12-30 08:01:09 769690366466208 _prepare_child(93043): exiting
2020-12-30 08:01:09 769690366496870 forkchild(parent): spawned child 93043
2020-12-30 08:01:09 769690366508135 forkchild(parent): calling _wait_for_child
2020-12-30 08:01:09 769690366519206 _wait_for_child: acquiring __child_exited
2020-12-30 08:01:09 769690366531657 _wait_for_child: acquired __child_exited
2020-12-30 08:01:09 769690366541766 _wait_for_child: entering waiting loop
2020-12-30 08:01:10 769691371715905 waiting for child 93043
2020-12-30 08:01:10 769691455821220 _child_handler: called for signal 20
2020-12-30 08:01:10 769691455837568 _child_handler: os.waitpid
2020-12-30 08:01:10 769691455883847 _child_handler: os.waitpid done
2020-12-30 08:01:10 769691455895347 _child_hander: signal.signal
2020-12-30 08:01:10 769691456167623 _child_handler: reaped child 93043 with status 0
2020-12-30 08:01:10 769691456186200 _child_handler.notify: acquire
2020-12-30 08:01:10 769691456199014 _child_handler.notify: notify_all
2020-12-30 08:01:10 769691456254245 _child_handler.notify: release
2020-12-30 08:01:10 769691456266416 _child_handler.notify: exiting
2020-12-30 08:01:10 769691456294165 _wait_for_child: releasing __child_exited
2020-12-30 08:01:10 769691456305366 _wait_for_child: released __child_exited
```

Blocked:
```
2020-12-30 08:01:10 769691548159847 forkchild: forking
2020-12-30 08:01:10 769691549260160 forkchild(93045): forked, calling _prepare_child
2020-12-30 08:01:10 769691550093820 _prepare_child(93045): entered
2020-12-30 08:01:10 769691550356223 _prepare_child(93045): exiting
2020-12-30 08:01:10 769691550387172 forkchild(parent): spawned child 93045
2020-12-30 08:01:10 769691550397995 forkchild(parent): calling _wait_for_child
2020-12-30 08:01:10 769691550408931 _wait_for_child: acquiring __child_exited
2020-12-30 08:01:10 769691550420683 _wait_for_child: acquired __child_exited
2020-12-30 08:01:10 769691550430310 _wait_for_child: entering waiting loop
2020-12-30 08:01:11 769692591142080 waiting for child 93045
2020-12-30 08:01:11 769692604191707 _child_handler: called for signal 20
2020-12-30 08:01:11 769692604207804 _child_handler: os.waitpid
2020-12-30 08:01:11 769692604244621 _child_handler: os.waitpid done
2020-12-30 08:01:11 769692604258039 _child_hander: signal.signal
2020-12-30 08:01:11 769692604554918 _child_handler: reaped child 93045 with status 0
2020-12-30 08:01:11 769692604569098 _child_handler.notify: acquire
2020-12-30 08:01:11 769692604582842 _child_handler.notify: notify_all
2020-12-30 08:01:11 769692604616941 _child_handler.notify: release
2020-12-30 08:01:11 769692604629145 _child_handler.notify: exiting
2020-12-30 08:01:12 769693612301562 waiting for child 93045
2020-12-30 08:01:13 769694627581299 waiting for child 93045
2020-12-30 08:01:14 769695690654857 waiting for child 93045
```
I don't understand why `_wait_for_child` is not notified while waiting.  Maybe I should check if they really use the same object id?
Also I wonder if there is something wrong with FreeBSD's Python implementation...  I'll try Python 3.9 next.

**Comment by ykasap** [comment]
I'm sorry I'm a bit confused in the previous post.  The recorded `_prepare_child` is from the parent.

**Comment by rpuntaie** [comment]
If timed out `wait()` could not acquire the lock. So if `notify_all()` happens while in the loop body, nobody is waiting.

**Comment by ykasap** [comment]
I see.  I misunderstood the behavior when `wait()` timed out.  I'll try the new code.

**Comment by ykasap** [comment]
The new code seems to work properly in my environment.  Now there is no wait loop, so I believe it won't hang.

I intentionally timed out the filter process by adding `sleep 5` before running `filter`.  `getmail6` exited abnormally with `getmailrc: operation error (got child pid 0, not 57179)` because `self.__child_pid` was not updated.  Probably there should be some clean-up after timeout.

Anyway my problem seems to be fixed.  Thank you very much for your kind support.

**Comment by rpuntaie** [comment]
Thank you for reporting and hanging on until fixed.
