### ISSUE TITLE
Retriever info in summary with --idle

### ISSUE THREAD

**Issue by vgropp** [getmail6/getmail6#57]
Hi,

i use several imap --idle accounts and syslog logging and systemd services. Currently I am missing the account name or something else to have some more info:

A typical log extract currently looks like
```
Jan  4 18:11:59 host getmail[1989578]: IDLE message received
Jan  4 18:11:59 host getmail[1989578]:   0 messages (0 bytes) retrieved, 2449 skipped
Jan  4 18:11:59 host getmail[2001160]: IDLE message received
Jan  4 18:12:01 host getmail[2001160]:   0 messages (0 bytes) retrieved, 25746 skipped
```

I would like to have something like 
`Jan  4 18:11:59 host getmail[1989578]:   0 messages (0 bytes) retrieved, 2449 skipped from account`

**Comment by rpuntaie** [comment]
Thanks.
