### ISSUE TITLE
getmail6: sometimes dies on running external filter program in version 6.13

### ISSUE THREAD

**Issue by sudipm-mukherjee** [getmail6/getmail6#64]
Its a bug report in https://bugs.debian.org/980056 after upgrade to 6.13 from 6.11.

Copying relevant part here:
```
A snip of log:

 2021-01-13 16:23:09 getmailOperationError error (child pid 83739 killed by signal 8)
 2021-01-13 16:23:09   1 messages (19425 bytes) retrieved, 0 skipped
 2021-01-13 16:24:50 Initializing SimpleIMAPSSLRetriever:vaclav.ovsik@gmail.com@imap.gmail.com:993:
 2021-01-13 16:24:55 getmailOperationError error (child pid 84030 killed by signal 8)
 2021-01-13 16:24:55   1 messages (19425 bytes) retrieved, 0 skipped
 2021-01-13 16:26:37 Initializing SimpleIMAPSSLRetriever:vaclav.ovsik@gmail.com@imap.gmail.com:993:
 2021-01-13 16:26:42 getmailOperationError error (child pid 84309 killed by signal 8)
 2021-01-13 16:26:42   1 messages (19425 bytes) retrieved, 0 skipped

corresponding rc section:

 [filter-1]
 type = Filter_external
 path = /usr/bin/spamassassin
 ignore_stderr = True
```

Same bug report shows when the user downgraded to 6.11 it works again.

**Comment by 9numbernine9** [comment]
I'm having this exact same issue as well (`getmail6 6.13`, FreeBSD `12.2-RELEASE-p1`). Downgrading to `6.11` appears to work for now.

**Comment by ykasap** [comment]
```
getmailcore/baseclasses.py:
   424      def _wait_for_child(self, childpid):
   425          self.__child_exited.acquire()
   426          if not self.__child_exited.wait(3):
   427              self.log.warning('stopped waiting for child %d' % childpid)
   428              self.__child_pid = childpid
   429              self.__child_status = os.WCONTINUED
(omit)
   442          if os.WIFSIGNALED(self.__child_status):
   443              raise getmailOperationError(
   444                  'child pid %d killed by signal %d'
   445                  % (self.__child_pid, os.WTERMSIG(self.__child_status))
   446              )
```

`os.WCONTINUED` is for option bits of `wait4()` and not for a wait status.  It is `8` in Linux and `4` in FreeBSD, and it it treated as a signal number.  I think `0` (`EXIT_SUCCESS`) is fine here.  Also, 3 seconds might be too short for some filter program.

**Comment by ykasap** [comment]
Now I think that it is better to wait much longer for the child to take care of the exit status, because `exitcode` is processed in `filter_message()` later to decide if the message should be kept or dropped.

**Comment by rpuntaie** [comment]
I will make a release with this change, because these problems are relevant.

**Comment by 9numbernine9** [comment]
Thank you for the quick fix! I just switched to this version and will report back if I encounter the issue any further!

**Comment by bronger** [comment]
Please also think of us pip users …

**Comment by rpuntaie** [comment]
Indeed. Sorry. It is in pypi now.

**Comment by TIS-Stefan** [comment]
Hello

I have a similar, but different issue
```
getmailOperationError error (child pid 26276 killed by signal 6)
2023-01-06 09:32:02   1 messages (158524 bytes) retrieved, 0 skipped
```
The process was in procmail and there is somewhere a memory corruption error. Seems to happen with some mails from google. Unfortunately, getmail stops processing following mails. 
Same, but with another signal and not in procmail happens with some particular emails from DHL with attachment. 
If I remove the emails in question from the inbox, then all works fine again.  I run the getmail6 every two minutes.

What I would like to do is:
If there is an error, ignore it and continue with next mails in the queue. Is that possible? How do I need to change the getmail6 code?

I see the logs anyway and therefore can handle that.

Thank you in advance!

Stefan

**Comment by Remmy** [comment]
Hi Stefan,

Please open a new issue for this instead of reopening an old one.

Thanks!
