### ISSUE TITLE
Migrating a getmail installation

### ISSUE THREAD

**Issue by DACN** [getmail6/getmail6#66]
I am migrating an old getmail4 installation, which is part of a mailman2 setup to a new server.
The work flow is:
    email -> gmail -> collected by getmail -> server -> mailman2 -> postfix -> users

Have rebuilt this ok for a test list mailman list. getmail6 works seamlessly as a drop in replacement.
I am concerned when migrating the two main lists that old messages should not be re-downloaded.

* The larger of the two lists has over 2500 messages on the gmail server
* The messages are left on the server, and are not marked as read  
    * except for the occasional instance when I pop in directly to see the messages on gmail)
* I had thought that the oldmail lists were there to stop multi-downloading
* BUT, the oldmail files are very small. For example 
* The  oldmail-pop.gmail.com-995-XXXmail@XXX.org.uk for the list with 2500 mail entries has only seven (7) lines in it 
* The other oldmail one is slightly larger and has thirty six (36) lines in it.

But reading the documentation, I don't see anything that gives me confidence that getmail will only download **relatively recent** emails, so that the size of the oldmail files does not have to be very large.

A bit confused.

**Comment by rpuntaie** [comment]
`oldmail-` files are filled only with those messages retrieved. If none was retrieved, the `oldmail-` file will be empty. All messages will be fetched.

I don't know whether getmail4 had the same `oldmail-` files, but probably yes.
So you could copy over that file, then the mails in there would not get fetched.

**Comment by emtiu** [comment]
For what it's worth, I've got some data for comparison: There's an oldmail file on my mail server which is just under 3 months old and has logged somewhere between 1,000 and 1,400 downloaded messages. It's 7.2kB in size and has 262 lines.

**Comment by DACN** [comment]
Thank you both. Your explanations coincide with how i expected matters to work. I think I am beginning to understand. The different behaviour seems to be caused by an unusual pop mailbox on gmail - which has two modes.

**Normal mode**  A POP client session starts with your mail client asking your Gmail mailbox for a list of messages that haven't yet been downloaded. After Gmail provides the list of messages to your mail client, your client will begin downloading them. In POP normal mode.  Once a message is downloaded, Gmail marks it as 'popped'.

**Recent mode** Gmail will present all messages ... from the last 30 days. This means that multiple POP clients can download the same messages

The default seems to be 'normal' mode, so that Gmail itself will only present 'unpopped' messages - even if you are switching clients. 

Even in recent mode - it appears that Gmail only offers messages which are under 30 days old.

I think the small sizes of the old files reflect the number of messages in each of the mailing lists in the last 30 days 

[Gmail documentation](https://support.google.com/a/answer/6089246?hl=en#zippy=%2Chow-does-normal-mode-work%2Chow-does-recent-mode-work%2Cre-downloading-messages-and-excluding-existing-messagesl)

Thanks

David

Messages sent from an email client don’t appear in the POP mail client in normal mode, but they do appear in recent mode. Messages sent from email clients are marked as popped, so they aren’t downloaded into the Inbox of POP mail clients.

**Comment by DACN** [comment]
Thanks - have posted a comment. I *think* it happens because of the strange
behaviour of the Gmail pop.

David
