### ISSUE TITLE
non-compliant e-mail header (in multidrop configuration) causes getmail to stop working

### ISSUE THREAD

**Issue by valbewe** [getmail6/getmail6#72]
The attached email causes getmail (in a multidrop configuration) to stop working. The root cause is probably the non-compliant email header:
[Urgent Notification Of Company Business Name Changes Asia.txt](https://github.com/getmail6/getmail6/files/6148863/Urgent.Notification.Of.Company.Business.Name.Changes.Asia.txt)
![getmail_rc_snipped](https://user-images.githubusercontent.com/55103055/111308159-a2b6ce00-865a-11eb-830b-e9f17f97c0aa.PNG)
![syslog_snipped](https://user-images.githubusercontent.com/55103055/111308166-a4809180-865a-11eb-9404-09629ff1fb62.PNG)

> “X-AntiAbuse: This header was added to track abuse, please include it with any abuse
	report
X-AntiAbuse: Primary Hostname - hst.sunucuyeri.net
X-AntiAbuse: Original Domain - test.at
X-AntiAbuse: Originator/Caller UID/GID - [47 12] / [47 12]
X-AntiAbuse: Sender Address Domain - alkawtharnational.com
X-Get-Message-Sender-Via: hst.sunucuyeri.net: none
X-Authenticated-Sender: hst.sunucuyeri.net:
X-Source:
X-Source-Args:
X-Source-Dir: ”
Content-Type: multipart/mixed; boundary="----=_NextPart_000_0012_A796884C.DCABE8FF"
**X-Envelope-To**: mail@test.at

I suspect that the two "DOUBLE QUOTATION MARK's" at the beginning and the end of the "anti-abuse-header" causing that the "python email.header.decode_header() function" cannot find the neccesary header field "envelope_recipient", which is located at the end of the header. Then getmail stopps working with the following error message:

> Mar 16 04:56:46 Mailserver getmail[985]: Configuration error: envelope_recipient specified header missing (X-Envelope-To:1)
Mar 16 04:56:46 Mailserver systemd[1]: mail.getmail.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 16 04:56:46 Mailserver systemd[1]: mail.getmail.service: Failed with result 'exit-code'.

The problem is that getmail gets stuck on this e-mail and therefore does not fetch any further e-mails from the server.
Are there any suggestions how to solve this problem?
Best regards,
valbewe

**Comment by rpuntaie** [comment]
Yes. This is a bug. Getmail should continue to fetch emails. 

Some details about my debugging:

  In `/usr/lib/python3.9/email/feedparser.py`
  
  ```
              if not headerRE.match(line):
  				...
  				break
  ```
  
  breaks out of the loop that parses the headers,
  because
  
  ```
   “X-AntiAbuse: This header was added to track abuse, please include it with any abuse
  ```
  
  cannot be matched against 
  
  ```python
  headerRE = re.compile(r'^(From |[\041-\071\073-\176]*:|[\t ])')
  ```


getmail does not continue,
because `getmailConfigurationError` is raised
instead of `getmailRetrievalError`.
`getmailConfigurationError` is not caught.

I'll catch it.

**Comment by valbewe** [comment]
Many Thanks! Do you think that it makes sense to modify `feedparser.py`, so that it also process emails with bad headers? I 've been using getmail for a couple of years now, and that is the first time I've faced such issues, but since so many spam and virus checkers adding their stuff to the mail header, could this be worth a try?

**Comment by rpuntaie** [comment]
That is python code. You could make a bug report there. They will probably argue that the header is not according RFC's.

Did you verify that getmail continues after meeting such a mail?
Can this be closed?

**Comment by valbewe** [comment]
Yes. Thanks again!
