### ISSUE TITLE
'ascii' codec can't encode characters in position 4017-4018

### ISSUE THREAD

**Issue by tbm** [getmail6/getmail6#74]
I'm getting the following error:

```
getmail version 6.15
Copyright (C) 1998-2020 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:tbm@cyrius.com@mail.gandi.net:993:
Delivery error (command procmail 29762 error (127, exec of command procmail failed ('ascii' codec can't encode characters in position 4017-4018: ordinal not in range(128))))
  msg 1/6 (12391 bytes), delivery error (command procmail 29762 error (127, exec of command procmail failed ('ascii' codec can't encode characters in position 4017-4018: ordinal not in range(128))))
```

I can make the email available if someone can tell me how to download it.

**Comment by emtiu** [comment]
The error message looks to me like it's procmail's problem. You could try to use another delivery command/target, and see if getmail can deliver the message then, without procmail onvolved.

(Before you do that, disable deleting of messages in the getmail config to avoid losing it for your main delivery target).

**Comment by tbm** [comment]
> The error message looks to me like it's procmail's problem. You could try to use another delivery command/target, and see if getmail can deliver the message then, without procmail onvolved.

Sorry, I forgot to mention that I tried this already.  I get the same problem with Maildir.

```
getmail version 6.15
Copyright (C) 1998-2020 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:tbm@cyrius.com@mail.gandi.net:993:
Delivery error (maildir delivery 35888 error (127, maildir delivery process failed ('ascii' codec can't encode characters in position 4017-4018: ordinal not in range(128))))
  msg 1/1 (12391 bytes), delivery error (maildir delivery 35888 error (127, maildir delivery process failed ('ascii' codec can't encode characters in position 4017-4018: ordinal not in range(128))))
  1 messages (12391 bytes) retrieved, 0 skipped from SimpleIMAPSSLRetriever:tbm@cyrius.com@mail.gandi.net:993
```

**Comment by rpuntaie** [comment]
The message would help me to find a solution. The charset of the mail is obviously not `ascii`. One can change the charset in Python's email Message class. Maybe I can find a general way to bypass such problems.

To get the mail, one try could be to add the following line in `getmail` before the line with the string `Delivery error`:

``` python
                        with open(os.path.expanduser('~/failing_mail.txt'),'w') as fm: fm.write(msg.content().as_string())
```

Else try [mbsync](https://isync.sourceforge.io/mbsync.html). A solutions [here](https://stackoverflow.com/questions/2230037/how-to-fetch-an-email-body-using-imaplib-in-python) might have the same problem. You could also use webmail of your provider.

**Comment by tbm** [comment]
@rpuntaie thanks, here's the email:

https://www.cyrius.com/tmp/failing_mail.txt

**Comment by rpuntaie** [comment]
It should work now. Would you give it a try?

**Comment by tbm** [comment]
Yes, it's working now, thank you!

**Comment by prinz3nroll3** [comment]
> The message would help me to find a solution. The charset of the mail is obviously not `ascii`. One can change the charset in Python's email Message class. Maybe I can find a general way to bypass such problems.
> 
> To get the mail, one try could be to add the following line in `getmail` before the line with the string `Delivery error`:
> 
> ```python
>                         with open(os.path.expanduser('~/failing_mail.txt'),'w') as fm: fm.write(msg.content().as_string())
> ```
> 
> Else try [mbsync](https://isync.sourceforge.io/mbsync.html). Getting the mail via [imaplib directly](https://stackoverflow.com/questions/2230037/how-to-fetch-an-email-body-using-imaplib-in-python) might have the same problem. You could also use webmail of your provider.

Hello,
i have the same issue. but i dont know where i have to add the line. can you give me an hint? thanks

**Comment by rpuntaie** [comment]
https://github.com/getmail6/getmail6/blob/9ad0603c8202f513aa78f37c77686aa30a7494c2/getmail#L323

**Comment by prinz3nroll3** [comment]
> https://github.com/getmail6/getmail6/blob/9ad0603c8202f513aa78f37c77686aa30a7494c2/getmail#L323

hello,
sorry again for the question. is this the right position? 

                     logline += ', deleted'

                    except getmailDeliveryError as o:
                        errorexit = True
                        with open(os.path.expanduser('~/failing_mail.txt'),'w') as fm: fm.write(msg.content().as_string())
                        log.error('Delivery error (%s)\n' % o)
                        info += ', delivery error (%s)' % o
                        if options['logfile']:
                            options['logfile'].write('Delivery error (%s)' % o)
                        if options['message_log_syslog']:
                            syslog.syslog(syslog.LOG_ERR,
                                          'Delivery error (%s)' % o)

                    except getmailFilterError as o:
