### ISSUE TITLE
6.16 release file changed after first tag

### ISSUE THREAD

**Issue by emtiu** [getmail6/getmail6#77]
After v6.16 was first tagged and signed, the release zip archive has changed once more:

Before:
`SHA256 (getmail6-getmail6-v6.16_GH0.tar.gz) = 4f87f9e3c111005ac13df93a7d9cf7572da2da98e771607b2948aed638833795`
`SIZE (getmail6-getmail6-v6.16_GH0.tar.gz) = 194300`

After:
`SHA256 (getmail6-getmail6-v6.16_GH0.tar.gz) = b92b9f3367d2f26b4fc9a53785d8f960f587e38d513d77bd3bc430ca4ea39d2a`
`SIZE (getmail6-getmail6-v6.16_GH0.tar.gz) = 194301`

**Comment by rpuntaie** [comment]
I did a bulk change from 2020 to 2021 and forgot to fix CHANGELOG.
Pull request #76 noticed it shortly after.
I wanted to fix it still in v6.16 and resigned v6.16 with the fix.
Sorry for the inconvenience.
