### ISSUE TITLE
Misplaced Content-Length header when passing to procmail

### ISSUE THREAD

**Issue by jborme** [getmail6/getmail6#8]
I get automated emails from a specific provider. When asked to pass through procmail, some headers get misplaced and the email is then not properly interpreted by neomutt.

The problem happens when using a simple no-op procmail config. It does not happen if asking getmail to deliver to Maildir directly. The problem only happens with the getmail 6.0 python3 port (synced as of now) and does not happen with getmail 5.14 (python2).

When recieving using getmail 6.0 (master) passing through procmail, the e-mail headers look like:
```
 0102017367b2723b-6139904f-bdb6-43eb-8b5d-bdbcd4856d51-000000@eu-west-1.amazonses.com  Sun Jul 19 16:30:22 2020
Content-Length: 199664

Return-Path: <
  0102017367b2723b-6139904f-bdb6-43eb-8b5d-bdbcd4856d51-000000@eu-west-1.amazonses.com>
Delivered-To: unknown
Received: from outlook.office365.com (40.101.92.18:995) by jerome.isoxys with
  POP3-SSL; 19 Jul 2020 15:30:22 -0000
Received: from AM0P194MB0388.EURP194.PROD.OUTLOOK.COM (2603:10a6:102:57::16)
...
X-Microsoft-Antispam-Message-Info: 
        =?utf-8?B?Q3JxRkVIZmlFUVNlZFRrcWxQdDIyTTVtZjh6ZWlBcWM1UEZpMkhyM0FGS3gz?=
...
MIME-Version: 1.0

----boundary_260_4a334f9f-8e86-412f-bd2e-3f7071f4e267
Content-Type: multipart/alternative;
 boundary=--boundary_259_847894fc-b9fb-452f-b01b-b152987b68f2
```

When receiving with getmail 6.0 with direct Maildir delivery, or when using getmail 5.14 passing through procmail, the message looks like (I ask the provider to resend the message, contents are similar but not absolutely identical)

```
Return-Path: <
  0102017367a3ac51-f7ea524b-3962-463b-ab48-2fb10270dc54-000000@eu-west-1.amazonses.com>
Delivered-To: unknown
Received: from outlook.office365.com (52.97.173.2:995) by jerome.isoxys with
  POP3-SSL; 19 Jul 2020 15:14:14 -0000
Received: from VI1P194MB0191.EURP194.PROD.OUTLOOK.COM (2603:10a6:100:18::28)
...
X-Microsoft-Antispam-Message-Info:      =?utf-8?B?byttQ1JZdnlkZmJJSktDZGxIRDdqRWNjMkZKZjNZem9uV242dEw5WVF0MnFm?=
MIME-Version: 1.0
Content-Length: 187703

----boundary_256_5f87e3f9-3690-41db-a8f2-859d2ff5fed6
Content-Type: multipart/alternative;
 boundary=--boundary_255_8da70375-a5d5-4147-aa2a-63b4d7668131
```

The difference is that with getmail 6, the Content-Length is placed on top instead of after MIME-Version. It also comes with a timestamp that duplicates the Return-Path contents. I haven't understood the purpose of all the headers. In some cases by moving the Content-Length after MIME-Version, I was able to make mutt understand the message, but in other cases it was not able to understand the From:, Delivered-To or Date fields.

The full headers are attached, with just the username edited to example.com
[delivery_Maildir.txt](https://github.com/getmail6/getmail6/files/4944031/delivery_Maildir.txt)
[delivery_procmail.txt](https://github.com/getmail6/getmail6/files/4944032/delivery_procmail.txt)

**Comment by jborme** [comment]
procmail.rc:

```
MAILDIR=/home/jerome/donnees/Mail/
INCLUDERC=/etc/procmailrc
DEFAULT=/home/jerome/donnees/Mail/inbox/
IDENTITY=$LOGNAME
LOGFILE=/home/jerome/.home/.procmail/$IDENTITY.log
VERBOSE=yes
```

getmailrc
```
[options]
verbose = 3
read_all = false
delete = false
delete_after = 25
message_log = ~/.getmail/log

recieved = true
delivered = true

[retriever]
type = SimplePOP3SSLRetriever
server = outlook.office365.com
username = YYY.YYY@example.com
password = ZZZ
port = 995

[destination]
type = Maildir
path = /home/jerome/donnees/Mail/inbox/
#type = MDA_external
#path = /usr/bin/procmail
#arguments = ("-f", "%(sender)", "-m", "~/.procmail/jerome.rc")
```

getmail log from the two emails attached in the previous message
```
2020-07-19 16:30:23 msg 582/582 (224068 bytes) msgid 58115 from <
 0102017367b2723b-6139904f-bdb6-43eb-8b5d-bdbcd4856d51-000000@eu-west-1.amazonses.com> delivered to MDA_external command procmail ()
2020-07-19 17:22:53 msg 583/583 (224051 bytes) msgid 58117 from <
 0102017367e26aca-2423034d-4e3b-44fe-8926-cd9e72cfa487-000000@eu-west-1.amazonses.com> delivered to Maildir /home/jerome/donnees/Mail/inbox/
```

procmail log (just one email since only one was delivered through procmail in this example)
```
procmail: [12017] Sun Jul 19 17:23:49 2020
procmail: Assigning "LASTFOLDER=/home/jerome/donnees/Mail/inbox/new/1595175829.12017_0.isoxys"
From 
 Subject: =?utf-8?B?RXVyb2NpcmN1aXRzIOKAkyBZb3VyIHByaWNlIHF1b3RhdGlv?=
  Folder: /home/jerome/donnees/Mail/inbox/new/1595175829.12017_0.isoxy	 199767
```

**Comment by rpuntaie** [comment]
I did some background research:

- The initial [From_ pseudo header](https://zer0.org/procmail/mini-faq.html#from--)
  is added by *procmail*.
  Getmail adds this, if there is `unixfrom` in the config, but default is `False`
  (See `include_from` in `message.py`).

- The `Return-Path` is added by *getmail*.

- `Content-Length` is not standard and
  [can cause problems](https://people.dsv.su.se/~jpalme/ietf/mail-headers/mail-headers.html)

  - `Content-Length` ... represents both the entity-length and the transfer-length.
  - `Content-Length` ... MUST NOT be sent if these two lengths are different

  `Content-Length` is a standard [http](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) header.

  `Content-Length` does not occur in the *getmail* sources.
  `Content-Length` thus is also added by *procmail*.

  In the *procmail* sources I have found:

       > (if you need the >From lines, you'll have to take any existing
       > Content-Lenght: field out of the header)

These *procmail* option are related to `Content-Length`:

       > -Y   Assume traditional Berkeley mailbox format, ignore any Content-Length: fields.
       >
       > -f fromwhom
       >      Causes  procmail  to  regenerate  the  leading `From ' line with fromwhom as the
       >      sender (instead of -f one could use the alternate and obsolete -r).  If fromwhom
       >      consists merely of a single `-', then procmail will only update the timestamp on
       >      the `From ' line (if present, if not, it will generate a new one).
       >
       > -o   Instead of allowing anyone to generate `From ' lines, simply override the fakes.

The basic problem I think is that `Content-Length` is larger.
Since you say that with *getmail 5.14 + procmail* there is no `Content-Length` at the beginning,
I guess *procmail* does add it,
because with *getmail 6* it does not fit the actual size.

I assume it relates to decoding.

In the latest commit
I removed the brute force decoding.

I could not reproduce your problem.
So I cannot verify, wether these changes solve your problem.
Can you try?

**Comment by jborme** [comment]
This new version seems to show another bug; it downloads the whole contents of the mailbox, even when emails were already seen.

**Comment by rpuntaie** [comment]
I just fixed you last issue.
Funny: Github automatically closes an issue if it finds `fix #X` in the commit statement.

Can you recheck regarding the actual problem here.

**Comment by jborme** [comment]
The last issue is indeed fixed. But now when passing through procmail, I get `NameError: name 'exit_width' is not defined.`

```Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.02
  Python version 3.7.8 (default, Jul 22 2020, 23:01:55) 
[GCC 10.1.0]

Unhandled exception follows:
    File "/usr/bin/getmail", line 883, in main
    success = go(configs, options.idle)
    File "/usr/bin/getmail", line 240, in go
    options['delivered_to'], options['received'])
    File "/usr/lib/python3.7/site-packages/getmailcore/destinations.py", line 108, in deliver_message
    return self._deliver_message(msg, delivered_to, received)
    File "/usr/lib/python3.7/site-packages/getmailcore/destinations.py", line 633, in _deliver_message
    lambda o,e: self._deliver_command(
    File "/usr/lib/python3.7/site-packages/getmailcore/baseclasses.py", line 475, in forkchild
    childfun(child.stdout, child.stderr)
    File "/usr/lib/python3.7/site-packages/getmailcore/destinations.py", line 634, in <lambda>
    msg, msginfo, delivered_to, received, o, e)
    File "/usr/lib/python3.7/site-packages/getmailcore/destinations.py", line 619, in _deliver_command
    exit_width(stderr, 'exec of command %s failed (%s)'
  NameError: name 'exit_width' is not defined

Please also include configuration information from running getmail
with your normal options plus "--dump".
Delivery error (command procmail 18214 error (4, b''))
  msg 669/669 (224145 bytes) from <
 0102017379017dc2-65e25ae3-b972-4ac5-ae6a-4522ce635eb8-000000@eu-west-1.amazonses.com>, delivery error (command procmail 18214 error (4, b''))
  1 messages (224145 bytes) retrieved, 668 skipped
Summary:
Retrieved 1 messages (224145 bytes) from SimplePOP3SSLRetriever:YYY.YYY@example.com@outlook.office365.com:995
```

**Comment by rpuntaie** [comment]
I fixed that and this time I also tested with procmail and a filter.

Could you retry regarding your issue?

**Comment by jborme** [comment]
This is strange, I have the same behaviour as in the beginning. First lines of the headers are:

```
 010201737df31569-5b91d407-2d7d-4df2-a17d-503bb5671452-000000@eu-west-1.amazonses.com  Fri Jul 24 00:12:41 2020
Content-Length: 199248

Return-Path: <
  010201737df31569-5b91d407-2d7d-4df2-a17d-503bb5671452-000000@eu-west-1.amazonses.com>
Delivered-To: unknown
```
[mail.txt](https://github.com/getmail6/getmail6/files/4969515/mail.txt)

**Comment by rpuntaie** [comment]
bb4e959 was the state before the experimental changes.
I reverted *master* to bb4e959.

I latest changes are now in the *develop* branch.

- bb4e959 (current head of master)
- f105f95 (current head of develop)

Master and develop branch have this issue.

Develop branch also has a problem with POP3:
UIDL command does not work:
'-ERR Unknown command: '
It works on master (bb4e959).

Only *develop* works with python 2.7.

I continue on top of *develop*.

Regarding this issue:

- Could you try *develop* with python 2.7?
  (Either change to `#!/usr/bin/env python2`, or do `python2 getmail ...`).

- Can you try the procmail options above?

- Did the message show any decoding issues?

- Could you send me a minimal message that produces the problem
  to puntaier dot roland at gmail dot com (I use this just for testing)?

**Comment by rpuntaie** [comment]
I found the POP3 UIDL bug. Master now equal to develop.

**Comment by jborme** [comment]
I tested with python 2.7.18 and 3.8.4. Works ok with python2 and gives the extra Content-Length header with python3. Output attached.

[mail_with_python2.7.txt](https://github.com/getmail6/getmail6/files/4974669/mail_with_python2.7.txt)
[mail_with_python3.8.txt](https://github.com/getmail6/getmail6/files/4974670/mail_with_python3.8.txt)

**Comment by rpuntaie** [comment]
On *develop* I removed `Content-Length`. What is the behavior with python 3 with this?

**Comment by jborme** [comment]
The answers to your questions:

Questions from Your comment 2020-07-25 11:51 UTC+1
I changed branch to develop and git pull says I am up to date.

The result is that the received e-mail starts with:
```
 010201738742050d-940c6f4c-3b43-444c-8b92-4239b1048c8b-000000@eu-west-1.amazonses.com  Sat Jul 25 19:35:38 2020
Return-Path: <
  010201738742050d-940c6f4c-3b43-444c-8b92-4239b1048c8b-000000@eu-west-1.amazonses.com>
Delivered-To: unknow
```
The leading space (one character) is the same as before, there is no Content-Length anymore, and the empty line is gone. mutt is still confused. If I remove the first line (the line before Return-Path that seem to duplicate its contents), then mutt understands the message.

Your questions from 2020-07-24 07:31 UTC+1
* first question answered already (my previous comment 2020-07-25 01:22 UTC+1)
* I am sorry not to understand which procmail options you are referring to.
* when the messages are not understood, they display raw in mutt (not decoded). If I delete the offending lines from the message (as explained just above) then the message is fine, including the MIME encoded PDF attachment.
* Instead of a minimal message, I sent you privately the credentials to a test mailbox with messages that trigger the problem.

**Comment by rpuntaie** [comment]
I think I got the bug. Please verify.

The sender field had a new line with Python 3.

>   Since the same code produced the problem with Python 3 but not with Python 2,
>   the reason was in the changes of the Python email library.
> 
>   Comparing the mail file produced by the two python versions
>   I found differences in the header formatting.
> 
>   - Python 3 uses tabs to indent not a space.
>   - Python 3 email puts more newline chars, especially immediately after the colon.
> 
>   Trying without the procmail `-f` option the `From_` line was not generated by procmail.
>   That made me think of differences in the `sender` field
>   and I recalled the different header formatting.

During this issue I made some code improvements not directly related to it.
Thanks for hanging on and for the testing infrastructure.

**Comment by jborme** [comment]
On my side it now works as well. Thanks a lot for spending the time to correct the bug.
