### ISSUE TITLE
Document how to tell which line of oldmail files corresponds to which message gotten

### ISSUE THREAD

**Issue by jidanni** [getmail6/getmail6#86]
A successful getmail run fetches messages, and updates the oldmail file.

But alas, there is no way, in hindsight, to know what each line referred to!

E.g., lines
```
11111111/22222^@333333
11111111/22223^@333333
11111111/22224^@333333
```

All we can do is say well we have three messages now on our disk.
But there is no way to know which was which!

Sure, we could use getmail --trace, but it is already too late.

**Comment by rpuntaie** [comment]
#81 fix records the message ID as `msgid:<msgid>` in the `Received` header.
#85 fix mentions that the message ID is in the oldmail.
