### ISSUE TITLE
Did the v6.16 tag change?

### ISSUE THREAD

**Issue by dotlambda** [getmail6/getmail6#87]
I think you changed the revision it points to. That's a big no-go for distributions that checksum the tarballs they download!

**Comment by Kr1ss-XD** [comment]
That's some weeks ago but yes, it changed at some point. For sure Roland didn't mean to cause any trouble.

Ref: https://github.com/getmail6/getmail6/issues/77

**Comment by rpuntaie** [comment]
I was aware that that was probably no good idea back then. Now I'm sure. Sorry for the inconvenience.
