### ISSUE TITLE
fetchmail feature: skip fetching read mail

### ISSUE THREAD

**Issue by mstsirkin** [getmail6/getmail6#89]
getmail relies on the oldmail files to know which mail to fetch.
a  mail marked read on the server is still fetched since it is not
in the oldmail file even if read_all if off.
this issue suggests that if read_all is false, getmail should skip
fetching read mail from the server.

**Comment by emtiu** [comment]
I don't think it's a good idea to skip downloading all mail that is marked as read on the server. Messages can be marked as read on the server for several reasons: they've been opened in webmail, processed by a filter or something. In those cases, it's not clear that getmail should skip downloading them.

As a compromise, maybe there could be a "skip_read" config option that would do this. For your use case, you could then set `read_all = False` and `skip_read = True`.

**Comment by rpuntaie** [comment]
`read_all` is defined as

```
     * read_all (boolean) — if set, getmail retrieves all available messages.
       If unset, getmail only retrieves messages it has not seen before.
       Default: True.
```

We cannot change the definition and behavior of existing config variables.

On stackoverflow I found an example how one could [get only new emails via imaplib](https://stackoverflow.com/questions/13210737/get-only-new-emails-imaplib-and-python).
There the search is for `(UNSEEN)`. 

`IMAP` search has further possibility.
If we implement something like this, we should go for a general solution.
Maybe an additional `imap_search` config option.

**Comment by mstsirkin** [comment]
I think this is a good idea, a new config variable would be sufficient and will avoid breaking existing configs. UNSEEN seems to be exactly what fetchmail is using.
