### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by solbu** [getmail6/getmail6#9]
Hi.
I am a packager for the Linux distro Mageia, and I just stumbled across your fork.

Do you plan to do a release / tag at any point? If so, when? :-)

**Comment by Kr1ss-XD** [comment]
+1

This would be great - I'm currently pinning the 'stable' package to bb4e959ebeea78ddc1569c8397f5aca7e1166e35 for the time being...

**Comment by rpuntaie** [comment]
I made a release.

**Comment by Kr1ss-XD** [comment]
Thank you !
