### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

### ISSUE THREAD

**Issue by mickael067** [getmail6/getmail6#91]
Recent bug since few day only with latest version.

```
getmail version 6.18.3
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:xxx@imap.xxx.net:993:

Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.18.3
  Python version 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

Unhandled exception follows:
    File "/usr/local/bin/getmail", line 983, in main
    success = go(configs, options.idle)
    File "/usr/local/bin/getmail", line 220, in go
    msg = retriever.getmsg(msgid)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 913, in getmsg
    return self._getmsgbyid(msgid)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 1617, in _getmsgbyid
    return self._getmsgpartbyid(msgid, part)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 1557, in _getmsgpartbyid
    msg.add_header('X-getmail-retrieved-from-mailbox',
    File "/usr/local/lib/python3.9/site-packages/getmailcore/message.py", line 228, in add_header
    self.__msg[name] = Header(content.rstrip())
    File "/usr/lib64/python3.9/email/header.py", line 217, in __init__
    self.append(s, charset, errors)
    File "/usr/lib64/python3.9/email/header.py", line 295, in append
    s = s.decode(input_charset, errors)
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

Please also include configuration information from running getmail
with your normal options plus "--dump".
-----
getmail version 6.18.3
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
getmail configuration:
  getmail version 6.18.3
  Python version 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  retriever:  SimpleIMAPSSLRetriever(ca_certs="None", certfile="None", getmaildir="/xxx/xxx", imap_on_delete="None", imap_search="None", keyfile="None", mailboxes="('ALL',)", move_on_delete="None", password="*", password_command="()", port="993", record_mailbox="True", server="imap.xxx.net", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_cram_md5="False", use_kerberos="False", use_peek="True", use_xoauth2="False", username="xxx")
  destination:  Mboxrd(locktype="lockf", path="/xxx/xxx", user="xxx")
  options:
    delete : False
    delete_after : 0
    delete_bigger_than : 0
    delivered_to : True
    fingerprint : False
    logfile : logfile(filename="/var/log/getmail.log")
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : /var/log/getmail.log
    message_log_syslog : False
    message_log_verbose : False
    read_all : False
    received : True
    skip_imap_fetch_size : False
    verbose : 1

-----
```

**Comment by rpuntaie** [comment]
You've configure `record_mailbox=True`, which does `msg.add_header('X-getmail-retrieved-from-mailbox',...`.
I do a check, whether it `is_ascii`, but it seem not to work for all cases.
Which Unicode characters are contained in your mailbox?

**Comment by rpuntaie** [comment]
Can your reproduce the problem and thus verify the solution?

**Comment by mickael067** [comment]
Sorry for the delay.
Put the record_mailbox=false (true is default value) solve the issue.

The code of the mail blocked receive after put "record_mailbox" to false 

`
Return-Path: <unknown>
Delivered-To: unknown
Received: from imap.xxx.net (xxx:993) by xxx.xxx.net with
  IMAP4-SSL getmail6 msgid:xxx/1; 18 Aug 2021 xx:xx:xx -0000
Date: Thu, xx Aug 2021 xx:xx:xx +0000
From: =?ISO-8859-1?Q?Mxxx=EBl?= <xxx@xxx.net>
To: =?ISO-8859-1?Q?Mxxx=EBl_xxx?= <xxx@xxx.eu>
Subject: Test
Message-ID: <xxx@xxx.net>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary=----SxxxY
Content-Transfer-Encoding: 7bit

------SxxxY
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test
--=20
Envoy=C3=A9 de mon appareil Android avec Courriel K-9 Mail=2E Veuillez exc=
user ma bri=C3=A8vet=C3=A9=2E
------SxxxY
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><body>Test<div style=3D'white-space: pre-wrap'><div cl=
ass=3D'k9mail-signature'>-- <br>Envoy=C3=A9 de mon appareil Android avec Co=
urriel K-9 Mail=2E Veuillez excuser ma bri=C3=A8vet=C3=A9=2E</div></div></b=
ody></html>
------SxxxY--


`

**Comment by rpuntaie** [comment]
I meant the name of the mailbox the mail came from. Common is `INBOX`, but yours is different and contains non-ascii. What is it?

I can reproduce `UnicodeDecodeError` only with Python2.7. But according to your report you use Python 3.9.6.

If you could temporarily make the changes of the above commit on your system and test with `record_mailbox=True`,
that would help to verify whether the change helps.

**Comment by mickael067** [comment]
I download not only `INBOX` but `ALL`, the this one is the send outbox call in French: "`Envoyés`".

With `record_mailbox=True`, the problem comes with a new mail sent and save into "`Envoyés`" folder that getmail fails to get.

`
getmail version 6.18.3
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:xxx@imap.xxx.net:993:
  msg 434/434 (117489 bytes) delivered

Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.18.3
  Python version 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

Unhandled exception follows:
    File "/usr/local/bin/getmail", line 983, in main
    success = go(configs, options.idle)
    File "/usr/local/bin/getmail", line 220, in go
    msg = retriever.getmsg(msgid)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 913, in getmsg
    return self._getmsgbyid(msgid)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 1617, in _getmsgbyid
    return self._getmsgpartbyid(msgid, part)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 1557, in _getmsgpartbyid
    msg.add_header('X-getmail-retrieved-from-mailbox',
    File "/usr/local/lib/python3.9/site-packages/getmailcore/message.py", line 228, in add_header
    self.__msg[name] = Header(content.rstrip())
    File "/usr/lib64/python3.9/email/header.py", line 217, in __init__
    self.append(s, charset, errors)
    File "/usr/lib64/python3.9/email/header.py", line 295, in append
    s = s.decode(input_charset, errors)
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

Please also include configuration information from running getmail
with your normal options plus "--dump".

getmail version 6.18.3
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
getmail configuration:
  getmail version 6.18.3
  Python version 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  retriever:  SimpleIMAPSSLRetriever(ca_certs="None", certfile="None", getmaildir="/xxx/getmail", imap_on_delete="None", imap_search="None", keyfile="None", mailboxes="('ALL',)", move_on_delete="None", password="*", password_command="()", port="993", record_mailbox="True", server="imap.xxx.net", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_cram_md5="False", use_kerberos="False", use_peek="True", use_xoauth2="False", username="xxx")
  destination:  Mboxrd(locktype="lockf", path="/xxx", user="xxx")
  options:
    delete : False
    delete_after : 0
    delete_bigger_than : 0
    delivered_to : True
    fingerprint : False
    logfile : logfile(filename="/var/log/getmail.log")
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : /var/log/getmail.log
    message_log_syslog : False
    message_log_verbose : False
    read_all : False
    received : True
    skip_imap_fetch_size : False
    verbose : 1
`

**Comment by rpuntaie** [comment]
Did you apply https://github.com/getmail6/getmail6/commit/1467883885d248cd9658d0d85aad283566cb5350?

**Comment by mickael067** [comment]
Sorry, I forget the patch.

The detail of the action done :

# cd /usr/local/lib/python3.9/site-packages/getmailcore/
# mv message.py message.py.save
# wget 'https://raw.githubusercontent.com/getmail6/getmail6/1467883885d248cd9658d0d85aad283566cb5350/getmailcore/message.py'
# ls -l message.py*
-rw-r--r-- 1 root root 8846 Jul  7 04:07 message.py
-rw-r--r-- 1 root root 8742 Aug 20 18:52 message.py.1

Set record_mailbox = true

Make new mail as test

getmail version 6.18.3
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:xxx@imap.xxx.net:993:

Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.18.3
  Python version 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

Unhandled exception follows:
    File "/usr/local/bin/getmail", line 983, in main
    success = go(configs, options.idle)
    File "/usr/local/bin/getmail", line 220, in go
    msg = retriever.getmsg(msgid)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 913, in getmsg
    return self._getmsgbyid(msgid)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 1617, in _getmsgbyid
    return self._getmsgpartbyid(msgid, part)
    File "/usr/local/lib/python3.9/site-packages/getmailcore/_retrieverbases.py", line 1557, in _getmsgpartbyid
    msg.add_header('X-getmail-retrieved-from-mailbox',
    File "/usr/local/lib/python3.9/site-packages/getmailcore/message.py", line 228, in add_header
    self.__msg[name] = Header(content.rstrip())
    File "/usr/lib64/python3.9/email/header.py", line 217, in __init__
    self.append(s, charset, errors)
    File "/usr/lib64/python3.9/email/header.py", line 295, in append
    s = s.decode(input_charset, errors)
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

Please also include configuration information from running getmail
with your normal options plus "--dump".
-----
getmail version 6.18.3
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
getmail configuration:
  getmail version 6.18.3
  Python version 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  retriever:  SimpleIMAPSSLRetriever(ca_certs="None", certfile="None", getmaildir="/xxx", imap_on_delete="None", imap_search="None", keyfile="None", mailboxes="('ALL',)", move_on_delete="None", password="*", password_command="()", port="993", record_mailbox="True", server="imap.xxx.net", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_cram_md5="False", use_kerberos="False", use_peek="True", use_xoauth2="False", username="xxx")
  destination:  Mboxrd(locktype="lockf", path="/xxx", user="xxx")
  options:
    delete : False
    delete_after : 0
    delete_bigger_than : 0
    delivered_to : True
    fingerprint : False
    logfile : logfile(filename="/var/log/getmail.log")
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : /var/log/getmail.log
    message_log_syslog : False
    message_log_verbose : False
    read_all : False
    received : True
    skip_imap_fetch_size : False
    verbose : 1

-----
