### ISSUE TITLE
'bad message from server!' and empty messages

### ISSUE THREAD

**Issue by richardweinberger** [getmail6/getmail6#94]
While fetching from IMAP something went wrong and getmail logged at lot of 'bad message from server!' messages.
Sadly it did continue, marked messages as fetched but the downloaded messages all consisting of:
```
Return-Path: <unknown>
X-getmail-retrieved-from-mailbox: INBOX

[None]
```

I'm tempted to treat such a bad message as fatal error.
What do you think?
```
diff --git a/getmailcore/_retrieverbases.py b/getmailcore/_retrieverbases.py
index a5d891457dc7..d88a75f320b4 100755
--- a/getmailcore/_retrieverbases.py
+++ b/getmailcore/_retrieverbases.py
@@ -1544,8 +1544,7 @@ class IMAPRetrieverBase(RetrieverSkeleton):
                 except Exception as o:
                     sbody = None
                 if not sbody:
-                    self.log.error('bad message from server!')
-                    sbody = bytes(response)
+                    raise getmailRetrievalError('bad message from server!')
                 msg = Message(fromstring=sbody)
             except TypeError as o:
                 # response[0] is None instead of a message tuple

```

**Comment by rpuntaie** [comment]
If only one message is corrupted, I think, one should not stop to retrieve the rest.

In your case more messages were corrupted.
But before doing any adjustments, one should find out what happened and whether that can occur to others, too.

If a message is corrupted, `corrupted_message()` should get called. There should not be just `[None]` in the message.

Maybe you can further investigate what happened.

**Comment by richardweinberger** [comment]
Sadly getmail delivered more than hundred corrupted messages to my Maildir. That's why I think aborting better.
On the server side clearly something bad happened. Investigation is still going on:
https://github.com/ProtonMail/proton-bridge/issues/220

Currently I'm fighting with bugs on both sides, client and server. :-(
