### ISSUE TITLE
Differences in messages from getmail5 vs getmail6

### ISSUE THREAD

**Issue by mgrant0** [getmail6/getmail6#97]
In researching some differences in email messages I was downloading using getmail from gmail, I spotted some differences between the message downloaded from gmail via the 'Download Original' message which gave me a .eml file vs. the message I got from getmail6 when I asked it to append it to an mbox file via an Mboxrd rule.

I started comparing getmail(5) and then though, well, let's see if getmail6 has different behavior and I think it may!

So I ran getmail5 and getmail6 against the same message.  It seems like getmail6 is messing with several of the headers, "cleaning up" whitespace and line wrapping.  Here is a diff from a spam message:

```
6c6,7
< X-Received: by 2002:a05:6512:b05:: with SMTP id w5mr4104459lfu.433.1635428004813;
---
> X-Received: by 2002:a05:6512:b05:: with SMTP id
>  w5mr4104459lfu.433.1635428004813;
16c17,18
< ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
---
> ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com;
>  s=arc-20160816;
27c29,30
<        spf=pass (google.com: domain of quzefiy@gmail.com designates 209.85.220.65 as permitted sender) smtp.mailfrom=quzefiy@gmail.com;
---
>        spf=pass (google.com: domain of quzefiy@gmail.com designates
>  209.85.220.65 as permitted sender) smtp.mailfrom=quzefiy@gmail.com;
29c32,33
< Received: from mail-sor-f65.google.com (mail-sor-f65.google.com. [209.85.220.65])
---
> Received: from mail-sor-f65.google.com (mail-sor-f65.google.com.
>  [209.85.220.65])
33c37,38
< Received-SPF: pass (google.com: domain of quzefiy@gmail.com designates 209.85.220.65 as permitted sender) client-ip=209.85.220.65;
---
> Received-SPF: pass (google.com: domain of quzefiy@gmail.com designates
>  209.85.220.65 as permitted sender) client-ip=209.85.220.65;
36c41,42
<        spf=pass (google.com: domain of quzefiy@gmail.com designates 209.85.220.65 as permitted sender) smtp.mailfrom=quzefiy@gmail.com;
---
>        spf=pass (google.com: domain of quzefiy@gmail.com designates
>  209.85.220.65 as permitted sender) smtp.mailfrom=quzefiy@gmail.com;
60,61c66,69
< X-Google-Smtp-Source: ABdhPJwqRn+qAMmOXubu++8bMSIZjwaVvi7uP53CapSJk0pYHWmrwEYJonC1P5m0Anyz9OgU9R5ssjz+mGCavNo5LrI=
< X-Received: by 2002:a05:6512:3f28:: with SMTP id y40mr4242433lfa.499.1635428003706;
---
> X-Google-Smtp-Source:
>  ABdhPJwqRn+qAMmOXubu++8bMSIZjwaVvi7uP53CapSJk0pYHWmrwEYJonC1P5m0Anyz9OgU9R5ssjz+mGCavNo5LrI=
> X-Received: by 2002:a05:6512:3f28:: with SMTP id
>  y40mr4242433lfa.499.1635428003706;
66,67c74,77
< Message-ID: <CAKgYqMW7dFQ=sg9cr2cP7khMLsxh_7JgRkiCutE3MugZOVyOJA@mail.gmail.com>
< Subject: You__may__contact__Maria__and__view__her__private__photos__and__videos
---
> Message-ID:
>  <CAKgYqMW7dFQ=sg9cr2cP7khMLsxh_7JgRkiCutE3MugZOVyOJA@mail.gmail.com>
> Subject:
>  You__may__contact__Maria__and__view__her__private__photos__and__videos
71c81,82
<       jaceyjroberts33@yahoo.com, irvanlaila@rocketmail.com, yournotme0001@gmail.com,
---
>       jaceyjroberts33@yahoo.com, irvanlaila@rocketmail.com,
>  yournotme0001@gmail.com,
```

I don't think getmail6 should be doing this!  I think it should produce exactly the same thing as the original getmail.

My tests were run using this getmailrc file:
```
[options]
delivered_to = false
received = false
delete = true

[retriever]
type = SimpleIMAPSSLRetriever
server = imap.gmail.com
username = user.name@gmail.com
port = 993
password = SECRET
mailboxes = ("[Gmail]/Spam",)
record_mailbox = false

[destination]
type = MultiDestination
destinations = ('[spamlog]',)

[spamlog]
type = Mboxrd
path = ~/getmail/spamlog
```

**Comment by Remmy** [comment]
>So I ran getmail5 and getmail6 against the same message.  It seems like
>getmail6 is messing with several of the headers, "cleaning up" whitespace and
>line wrapping.

I think the standards allow for headers to be rewrapped "on the fly" and that
this might be a difference in how the python email libraries handle this between
version 2 and 3. Both approaches are equally valid.

**Comment by mgrant0** [comment]
The standard may allow for this but this isn't my point.  The point is that this should have the same behavior as the original getmail and it does not.

**Comment by Remmy** [comment]
>The standard may allow for this but this isn't my point.  The point is that
>this should have the same behavior as the original getmail and it does not.

I don't mean this as harsh as it might sound, but why should it be exactly the
same behaviour?

Both ways (as I understand it) result in the message being validly and correctly
downloaded and neither way is more right than the other.

Anyways, that is my understanding of the standards involved, perhaps Roland has
a different view based on his knowledge of the code.

**Comment by mgrant0** [comment]
In my case, I am submitting messages to spam reporters.  I can't have the message modified in any way.  It will affect things like dkim headers and checksums of the message.  It's impossible to know what happens to the message once it's reported but it's not fair if it gets modified when they ask me to forward it exactly as it was received.

**Comment by Remmy** [comment]
I understand. As far as I understand though, DKIM-signatures do account for this
and allows for this whitespace folding (and even case changes of the headers
before the colon) as this is all permissible per standards.

Note that I am not a DKIM-guru, I just notice that the RFC for it seems to spend
a lot of time on this subject.

**Comment by rpuntaie** [comment]
I did not do any changes in `getmail` regarding headers. `getmail` is a wrapper around the Python email library. So Python 3 `email` has changed here with respect to Python 2.
