### ISSUE TITLE
duplicate emails

### ISSUE THREAD

**Issue by leonhedding** [getmail6/getmail6#98]
We are experiencing random and periodic duplication of email when using systemd, IMAP to Office 365 and using OAuth. We are running getmail version 6.18.4. Our getmailrc is configured as follows.

[destination]
type = MDA_external
path = /file/path/to/working/executable
user = apache
group = apache

[options]
verbose = 2
read_all = True
delete = True
timeout = 60
message_log_syslog = 1
message_log_verbose = 1

I attach the last error we had in our log file. There literally were that many messages in the log file in a second before it failed. Why it happened is beyond me.

[getmail-error.txt](https://github.com/getmail6/getmail6/files/7470633/getmail-error.txt)

**Comment by rpuntaie** [comment]
This might be the same as #94.

**Comment by leonhedding** [comment]
No, the messages were not corrupted. At this point we have reverted to getmail and will stick with that. We need something that is more stable for our critical processes.

**Comment by rpuntaie** [comment]
Sorry changed the text while looking through the code. Your last comment might not refer to the edited text.

**Comment by rpuntaie** [comment]
Your message refers to my first guess that it might overlap with the #94 report. I agree that it does not.
