### ISSUE TITLE
Connection to outlook.office365.com problems.

### ISSUE THREAD

**Issue by Mohammad-Asiri** [getmail6/getmail6#99]
Hi there

Since the last two days I have been having problems using getmail6 to connect to the outlook.office365.com server. I am trying to connect with secure IMAP, but getting the following message in the log file.
> 2021-11-25 08:48:13 socket error ([Errno 104] Connection reset by peer)

I am trying to use getmail6 to download emails and then run a script to process them automatically.

My getmailrc file is as follows:
```
[retriever]
type = SimpleIMAPSSLRetriever 
server = outlook.office365.com
username = something@somewhere.net
port = 993
password = something
timeout = 180

[destination]
type = Maildir
path = /home/masiri/Maildir-DDR/
user = masiri

[options]
verbose = 2
read_all = false
delete = false
max_messages_per_session = 5000
message_log = /home/masiri/logs/getmail.log
```

I have tried a few commands to get to the bottom of the issue.
```
:~$ openssl s_client -connect outlook.office365.com:993
CONNECTED(00000003)
write:errno=104

with -tls1_2
~$ openssl s_client -tls1_2 -connect outlook.office365.com:993
CONNECTED(00000003)
write:errno=104

and when using -tls1_3
:~$ openssl s_client -tls1_3 -connect outlook.office365.com:993
CONNECTED(00000003)
write:errno=0
```

It seems to me the outlook server accepts only tls v1.3 for connections, is that correct?

I have setup Thunderbird to the same server, and it connects and downloads the emails.

How do I fix this connection problem? My system is as follows:
```
Ubuntu Server
OS: Ubuntu 20.04.3 LTS x86_64
Kernel: 5.4.0-90-generic
Shell: bash 5.0.17
Memory: 190MiB / 7961MiB
```

Thanks in advance.

**Comment by Kr1ss-XD** [comment]
Hi @Mohammad-Asiri !

I'm getting the very same error once in a while when trying to connect to `outlook.office365.com` on port 993 via `mbsync`. Although I don't have an actual fix, there is a workaround that works for me.

I found that when using the `imap-mail.outlook.com` domain instead, I was able to sync my mail. Weirdly enough, some weeks later I got the same error and was then able to workaround by changing the domain back to 'outlook.office365.com`.

Hope this helps.

**Comment by rpuntaie** [comment]
getmail6 doc does not mention TLSv1_3,
but in Python3.9's ssl library there is TLSv1_3.
getmail6 has the `ssl_version` configuration value.
But getmail6 has also `check_ssl_version`.
I'm not sure whether TLSv1_3 gets through there.

It would be great if you could experiment with ssl_version
and report if you found a config that works.

If code changes are needed, a pull request is very welcome.

**Comment by Mohammad-Asiri** [comment]
> Hi @Mohammad-Asiri !
> 
> I'm getting the very same error once in a while when trying to connect to `outlook.office365.com` on port 993 via `mbsync`. Although I don't have an actual fix, there is a workaround that works for me.
> 
> I found that when using the `imap-mail.outlook.com` domain instead, I was able to sync my mail. Weirdly enough, some weeks later I got the same error and was then able to workaround by changing the domain back to 'outlook.office365.com`.
> 
> Hope this helps.

I tried the `imap-mail.outlook.com` server, but got the same error message. I think that Microsoft is forcing people to use the latest TLS version.

Thanks for your help
